// ═══════════════════════════════════════════════════════════════════════════
// CHAPTER 3: RELATIONSHIPS - The Art of Human Connection
// ═══════════════════════════════════════════════════════════════════════════

import type { FlexibleLesson, FlexibleChapter, LessonStep } from '@/types/lessons';

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 11: THE MIRROR EFFECT
// ─────────────────────────────────────────────────────────────────────────────

const lesson11_MirrorEffect: FlexibleLesson = {
  id: 'modern-11-mirror-effect',
  slug: 'mirror-effect',
  order: 1,
  title: 'The Mirror Effect',
  subtitle: 'Others reflect what you project',
  description: 'Discover how changing yourself changes everyone around you.',
  coreConceptTag: 'projection',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '🪞', color: '#a855f7' },
  teaserText: "Tomorrow you'll discover why the people who frustrate you most might be your greatest teachers.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "There's someone who frustrates you. Someone who seems impossible. Their behavior grates on you in a way that feels disproportionate to what they actually did.\n\nHere's the uncomfortable truth: the people who trigger us most are often showing us something about ourselves we don't want to see.",
      subtext: "The world is a mirror, not a window.",
      continueLabel: "I'm curious",
      mood: 'curiosity',
      nextStepId: 'trigger-check',
    },
    {
      id: 'trigger-check',
      type: 'resonanceCheck',
      prompt: "What triggers you in other people?",
      instruction: "Tap what sets you off",
      options: [
        { id: 'arrogance', text: 'Arrogance or ego' },
        { id: 'laziness', text: 'Laziness or lack of effort' },
        { id: 'dishonesty', text: 'Dishonesty or manipulation' },
        { id: 'neediness', text: 'Neediness or clinginess' },
        { id: 'judgment', text: 'Being judgmental' },
        { id: 'selfishness', text: 'Selfishness' },
        { id: 'victimhood', text: 'Playing the victim' },
        { id: 'control', text: 'Being controlling' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'triggers',
      nextStepId: 'trigger-scale',
    },
    {
      id: 'trigger-scale',
      type: 'scaleRating',
      prompt: "How intensely does this trigger you?",
      lowLabel: 'Mildly annoyed',
      highLabel: 'Deeply enraged',
      steps: 5,
      storeAs: 'trigger-intensity',
      responsesByRange: {
        low: "A mild trigger still has something to teach you.",
        mid: "That level of reaction usually means something deeper is at play.",
        high: "The stronger the reaction, the bigger the mirror. Something important is being reflected here.",
      },
      nextStepId: 'mirror-insight',
    },
    {
      id: 'mirror-insight',
      type: 'insight',
      text: "Carl Jung called this 'shadow work.' What we react to strongly in others often exists within us — either as something we fear, something we deny, or something we've buried.\n\nThe anger that enrages us in someone else? We might fear our own anger. The laziness we judge? Perhaps we secretly fear we're not working hard enough.",
      source: 'Carl Jung',
      style: 'principle',
      followUp: "This isn't blame — it's liberation. When you see your triggers as teachers, you gain power over your reactions.",
      nextStepId: 'mirror-choice',
    },
    {
      id: 'mirror-choice',
      type: 'choice',
      instruction: 'Be brave with this one',
      question: 'What might your trigger be reflecting about you?',
      options: [
        {
          id: 'explore',
          label: "I see it — there's something about me in this",
          subtext: "I'm willing to look deeper",
          nextStepId: 'explore-tapflow',
          storeAs: 'mirrorResponse',
        },
        {
          id: 'observe',
          label: "I'm not sure yet — but I'm open to seeing",
          subtext: "I'll observe without forcing it",
          nextStepId: 'observe-tapflow',
          storeAs: 'mirrorResponse',
        },
      ],
    },
    {
      id: 'explore-tapflow',
      type: 'tapFlow',
      title: 'Looking in the Mirror',
      instructions: [
        'Hold that frustrating quality in your mind.',
        'Now ask: Where does this exist in ME?',
        'Perhaps in a different form...',
        '...or perhaps you fear becoming this way.',
        'Or maybe you once were this way and judge yourself.',
        'What is this person showing you about yourself?',
        'This isn\'t about blame. It\'s about seeing.',
        'What you can see, you can heal.',
        'What you deny, controls you.',
      ],
      style: 'grounding',
      nextStepId: 'healing-affirmation',
    },
    {
      id: 'observe-tapflow',
      type: 'tapFlow',
      title: 'The Observer\'s Stance',
      instructions: [
        'You don\'t have to force an insight.',
        'Sometimes the mirror takes time to clear.',
        'For now, just notice your reactions.',
        'The next time this person frustrates you...',
        '...pause before reacting.',
        'Ask yourself: what am I really feeling?',
        'Not what they did. What I\'m feeling.',
        'That space between trigger and response...',
        '...is where all your power lives.',
      ],
      style: 'grounding',
      nextStepId: 'healing-affirmation',
    },
    {
      id: 'healing-affirmation',
      type: 'affirmation',
      preText: "You looked where most people refuse to look.",
      statement: "My triggers are my teachers. What I react to in others shows me where I still need to grow.",
      confirmLabel: "I accept this mirror",
      style: 'strength',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What did you discover about your triggers? What might they be reflecting about your own fears or hidden qualities?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Carl Jung wrote: 'Everything that irritates us about others can lead us to an understanding of ourselves.'\n\nThe Stoics said we cannot control others, only ourselves. Today you went further — you saw that others are often reflecting what needs attention within us. That's not comfortable. But it's liberating.",
      source: 'Carl Jung',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Every person who frustrates you is offering a lesson. Not a comfortable truth, but a liberating one. You had the courage to look. Most people never do.",
        ],
        byChoice: {
          explore: [
            "You were willing to look in the mirror. That takes real courage. What you discovered today — that your triggers reflect something in you — is the beginning of genuine self-knowledge. Keep looking. The mirror always has more to show.",
          ],
          observe: [
            "You chose to observe without forcing insight. That's wisdom. The mirror will clear in its own time. For now, just practice the pause — that space between trigger and reaction. That space is where your freedom lives.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 12: RADICAL HONESTY
// ─────────────────────────────────────────────────────────────────────────────

const lesson12_RadicalHonesty: FlexibleLesson = {
  id: 'modern-12-radical-honesty',
  slug: 'radical-honesty',
  order: 2,
  title: 'Radical Honesty',
  subtitle: 'The truth will set you free (but first it will make you uncomfortable)',
  description: 'Learn why small lies imprison you and radical honesty liberates.',
  coreConceptTag: 'honesty',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '🔓', color: '#06b6d4' },
  teaserText: "Tomorrow you'll understand why small lies build prisons and radical honesty sets you free.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Every 'I'm fine' when you're not. Every 'Sure, no problem' when it is. Every polite lie. They seem harmless.\n\nBut each one is a tiny brick in a prison you're building around yourself. The weight of small deceptions compounds daily.",
      subtext: "What would it feel like to put down the mask?",
      continueLabel: "I feel that weight",
      mood: 'tension',
      nextStepId: 'honesty-check',
    },
    {
      id: 'honesty-check',
      type: 'resonanceCheck',
      prompt: "Where are you being dishonest?",
      instruction: "Tap what rings true — this is private",
      options: [
        { id: 'fine', text: 'I say I\'m fine when I\'m not' },
        { id: 'overcommit', text: 'I agree to things I don\'t want to do' },
        { id: 'feelings', text: 'I hide my real feelings' },
        { id: 'opinions', text: 'I hold back my real opinions' },
        { id: 'needs', text: 'I pretend I don\'t need help' },
        { id: 'mask', text: 'I wear a mask at work or socially' },
        { id: 'self', text: 'I lie to myself about what I want' },
        { id: 'avoid', text: 'I avoid difficult conversations' },
      ],
      minSelections: 1,
      maxSelections: 4,
      storeAs: 'dishonesty-areas',
      nextStepId: 'honesty-scale',
    },
    {
      id: 'honesty-scale',
      type: 'scaleRating',
      prompt: "How honest are you with yourself and others on a daily basis?",
      lowLabel: 'Mostly filtered',
      highLabel: 'Radically honest',
      steps: 5,
      storeAs: 'honesty-level',
      responsesByRange: {
        low: "You're carrying a lot of masks. No wonder you're exhausted. Today we start taking them off.",
        mid: "You're honest sometimes, filtered other times. Let's explore what you're hiding and why.",
        high: "You value truth. Today we go even deeper — to the truths you hide from yourself.",
      },
      nextStepId: 'core-insight',
    },
    {
      id: 'core-insight',
      type: 'insight',
      text: "Radical honesty isn't about being brutal. It's about being real. The energy we spend managing impressions and protecting lies could be spent on actual living.\n\nWhen you tell the truth, you stop carrying the burden of maintaining the fiction.",
      source: 'Brad Blanton',
      sourceBook: 'Radical Honesty',
      style: 'principle',
      followUp: "The truth doesn't always feel good. But it always feels lighter than the lie.",
      nextStepId: 'honesty-choice',
    },
    {
      id: 'honesty-choice',
      type: 'choice',
      instruction: 'Which truth needs air?',
      question: 'What kind of honesty do you need most right now?',
      options: [
        {
          id: 'others',
          label: 'Honesty with someone else',
          subtext: "There's a conversation I've been avoiding",
          nextStepId: 'others-tapflow',
          storeAs: 'honestyTarget',
        },
        {
          id: 'self',
          label: 'Honesty with myself',
          subtext: "There's something I've been denying",
          nextStepId: 'self-tapflow',
          storeAs: 'honestyTarget',
        },
      ],
    },
    {
      id: 'others-tapflow',
      type: 'tapFlow',
      title: 'The Honest Conversation',
      instructions: [
        'Think of the person you need to be honest with.',
        'What would you say if there were no consequences?',
        'Not the cruel version. The honest version.',
        'Kind but clear. Gentle but real.',
        "The conversation may be uncomfortable for 5 minutes.",
        "But the freedom it creates lasts far longer.",
        "Every honest word spoken is a brick removed from your prison.",
        "You don't owe anyone a comfortable lie.",
        "You owe yourself — and them — the truth.",
      ],
      style: 'fearless',
      nextStepId: 'honesty-affirmation',
    },
    {
      id: 'self-tapflow',
      type: 'tapFlow',
      title: 'The Inner Truth',
      instructions: [
        'Close your eyes for a moment.',
        'What have you been pretending not to know?',
        "There's a truth you've been avoiding.",
        "It's been whispering to you for a while.",
        "Maybe you know exactly what it is right now.",
        "Naming it doesn't mean acting on it today.",
        "But denying it takes energy you could use for living.",
        "The truth you tell yourself is the foundation of everything.",
        "Without that, nothing else is real.",
      ],
      style: 'grounding',
      nextStepId: 'honesty-affirmation',
    },
    {
      id: 'honesty-affirmation',
      type: 'affirmation',
      preText: "You chose truth over comfort.",
      statement: "I will stop protecting lies and start living in truth. The weight of honesty is lighter than the weight of pretending.",
      confirmLabel: "I choose honesty",
      style: 'commitment',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What would your life look like if you were radically honest? What truth is most important for you to embrace?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Brad Blanton wrote: 'Telling the truth is the fastest path to real intimacy and the only reliable foundation for a life that works.'\n\nEvery honest word spoken is a brick removed from your prison. You may not have spoken it yet, but you've acknowledged it. That's the first step to freedom.",
      source: 'Brad Blanton',
      sourceBook: 'Radical Honesty',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "The truth sets you free, but first it scares you. Today you looked at something you've been avoiding. That takes courage most people never find.",
        ],
        byChoice: {
          others: [
            "You chose truth over comfort in a relationship. Whatever happens in that conversation, you'll be lighter for having it. The weight of unspoken words is heavier than any difficult conversation.",
          ],
          self: [
            "The hardest person to be honest with is yourself. The lies we tell ourselves are the most insidious because we believe them. Today you cracked the illusion. That crack will grow.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 13: BOUNDARIES WITH GRACE
// ─────────────────────────────────────────────────────────────────────────────

const lesson13_BoundariesGrace: FlexibleLesson = {
  id: 'modern-13-boundaries-grace',
  slug: 'boundaries-grace',
  order: 3,
  title: 'Boundaries with Grace',
  subtitle: 'Saying no without guilt',
  description: "Learn why healthy boundaries aren't selfish — they're essential.",
  coreConceptTag: 'boundaries',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '🛡️', color: '#f59e0b' },
  teaserText: "Tomorrow you'll learn how to say 'no' without guilt - the skill that protects everything you care about.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You said yes when you meant no. Again. You overcommitted, overextended, and now you resent the very things you agreed to.\n\nThe inability to set boundaries doesn't make you kind. It makes you dishonest — and eventually, exhausted.",
      subtext: "'No' is a complete sentence.",
      continueLabel: "I know this pattern",
      mood: 'tension',
      nextStepId: 'boundary-check',
    },
    {
      id: 'boundary-check',
      type: 'resonanceCheck',
      prompt: "Where are your boundaries being crossed?",
      instruction: "Tap all that apply",
      options: [
        { id: 'time', text: 'My time is constantly stolen' },
        { id: 'energy', text: 'People drain my energy' },
        { id: 'favors', text: 'I can\'t say no to favors' },
        { id: 'work', text: 'Work invades my personal life' },
        { id: 'emotions', text: 'I absorb everyone\'s emotions' },
        { id: 'guilt', text: 'I feel guilty when I prioritize myself' },
        { id: 'toxic', text: 'I tolerate toxic behavior' },
        { id: 'expectations', text: 'Others\' expectations run my life' },
      ],
      minSelections: 1,
      maxSelections: 4,
      storeAs: 'boundary-violations',
      nextStepId: 'boundary-scale',
    },
    {
      id: 'boundary-scale',
      type: 'scaleRating',
      prompt: "How often do you say yes when you really mean no?",
      lowLabel: 'Rarely',
      highLabel: 'Almost always',
      steps: 5,
      storeAs: 'yes-addiction',
      responsesByRange: {
        low: "You already protect your energy. Today we refine and strengthen those walls.",
        mid: "Sometimes you hold the line, sometimes you cave. Let's make the boundary consistent.",
        high: "You've been giving yourself away. Today, you start taking yourself back.",
      },
      nextStepId: 'core-insight',
    },
    {
      id: 'core-insight',
      type: 'insight',
      text: "Healthy boundaries aren't walls — they're filters. They protect your energy while allowing genuine connection.\n\nEvery 'yes' to something is a 'no' to something else. When you say yes to everyone else, you're saying no to yourself.",
      style: 'principle',
      followUp: "Guilt about boundaries is a lie we tell ourselves. People-pleasing is often about our need to be liked, not genuine generosity.",
      nextStepId: 'script-tapflow',
    },
    {
      id: 'script-tapflow',
      type: 'tapFlow',
      title: 'The Boundary Script',
      instructions: [
        'Here are words for when you need them:',
        '"I appreciate you thinking of me, but I can\'t commit to that right now."',
        '"That doesn\'t work for me."',
        '"I need to check with myself before I say yes."',
        '"I love you, AND I need space right now."',
        '"No." (A complete sentence.)',
        'You don\'t owe lengthy explanations.',
        'Kind but clear. Firm but gentle.',
        'Your energy is not unlimited. Protect it.',
      ],
      closingText: "Boundaries are the immune system of the soul.",
      style: 'fearless',
      nextStepId: 'boundary-choice',
    },
    {
      id: 'boundary-choice',
      type: 'choice',
      instruction: 'What boundary do you need most?',
      question: 'Where will you start protecting your energy?',
      options: [
        {
          id: 'specific',
          label: 'A specific person or situation',
          subtext: "I know exactly where I need to draw the line",
          nextStepId: 'specific-affirmation',
          storeAs: 'boundaryTarget',
        },
        {
          id: 'general',
          label: 'My overall pattern of saying yes',
          subtext: "I need to change the habit itself",
          nextStepId: 'general-affirmation',
          storeAs: 'boundaryTarget',
        },
      ],
    },
    {
      id: 'specific-affirmation',
      type: 'affirmation',
      preText: "You know where the line needs to be drawn.",
      statement: "I will protect my energy in this situation. Saying no is not selfish — it's honest. And honest is what I choose to be.",
      confirmLabel: "I will set this boundary",
      style: 'strength',
      nextStepId: 'reflection',
    },
    {
      id: 'general-affirmation',
      type: 'affirmation',
      preText: "You're changing the pattern, not just the moment.",
      statement: "From now on, I pause before saying yes. I check with myself first. My energy is precious, and I will treat it that way.",
      confirmLabel: "I choose myself too",
      style: 'commitment',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "How does it feel to have words for protecting your energy? What would change if you consistently honored your own boundaries?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Bren\u00e9 Brown wrote: 'Daring to set boundaries is about having the courage to love ourselves even when we risk disappointing others.'\n\nThe people who respect you will respect your boundaries. The ones who don't were benefiting from your lack of them. Either way, you discover the truth.",
      source: 'Bren\u00e9 Brown',
      sourceBook: 'Daring Greatly',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Boundaries are the immune system of the soul. Without them, you absorb everyone else's demands until there's nothing left of you. You just fortified your defenses.",
        ],
        byChoice: {
          specific: [
            "You identified exactly where the line needs to be drawn. Having the words ready is half the battle. When the moment comes, you'll have your script. Use it. Your future self will thank you.",
          ],
          general: [
            "You chose to change the pattern, not just a single situation. That's the deeper work. The habit of pausing before saying yes will transform your relationships and protect your energy for what truly matters.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 14: THE EMPATHY SHIFT
// ─────────────────────────────────────────────────────────────────────────────

const lesson14_EmpathyShift: FlexibleLesson = {
  id: 'modern-14-empathy-shift',
  slug: 'empathy-shift',
  order: 4,
  title: 'The Empathy Shift',
  subtitle: 'Seek first to understand',
  description: 'Transform conflict by understanding before demanding to be understood.',
  coreConceptTag: 'empathy',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '💗', color: '#ec4899' },
  teaserText: "Tomorrow you'll learn the single shift that transforms conflict into connection.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "In most conflicts, both people are fighting to be understood. Nobody is trying to understand. The result: two monologues disguised as a conversation, both parties walking away feeling unheard.",
      subtext: "The person who understands first wins the relationship, not the argument.",
      continueLabel: "I've felt this",
      mood: 'tension',
      nextStepId: 'conflict-check',
    },
    {
      id: 'conflict-check',
      type: 'resonanceCheck',
      prompt: "What kind of conflicts do you face?",
      instruction: "Tap what sounds familiar",
      options: [
        { id: 'partner', text: 'Conflict with a partner or spouse' },
        { id: 'family', text: 'Family disagreements' },
        { id: 'friend', text: 'Tension with a friend' },
        { id: 'coworker', text: 'Workplace conflicts' },
        { id: 'authority', text: 'Conflict with authority' },
        { id: 'stranger', text: 'Frustration with strangers' },
        { id: 'self', text: 'Inner conflict with myself' },
        { id: 'values', text: 'People with different values' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'conflict-types',
      nextStepId: 'empathy-scale',
    },
    {
      id: 'empathy-scale',
      type: 'scaleRating',
      prompt: "In conflict, how often do you try to understand the other person first?",
      lowLabel: 'Almost never',
      highLabel: 'Almost always',
      steps: 5,
      storeAs: 'empathy-level',
      responsesByRange: {
        low: "You fight to be understood. Most people do. Today we flip that pattern.",
        mid: "Sometimes you listen first, sometimes you argue first. Let's make empathy your default.",
        high: "You already lead with understanding. Today we deepen that skill even further.",
      },
      nextStepId: 'core-insight',
    },
    {
      id: 'core-insight',
      type: 'insight',
      text: "'Seek first to understand, then to be understood.'\n\nThis isn't just politeness. It's strategy. When people feel truly heard, their defenses drop. Only then can they hear you.",
      source: 'Stephen Covey',
      sourceBook: 'The 7 Habits of Highly Effective People',
      style: 'principle',
      followUp: "Empathy isn't agreement. You can understand someone completely and still disagree. But understanding opens doors that judgment keeps closed.",
      nextStepId: 'perspective-tapflow',
    },
    {
      id: 'perspective-tapflow',
      type: 'tapFlow',
      title: 'Walking in Their Shoes',
      instructions: [
        'Think of someone you\'re in conflict with.',
        'Now try something radical: see through their eyes.',
        'What are they afraid of?',
        'What do they need that they\'re not getting?',
        'What experience shaped the way they see this?',
        'Maybe they\'re wrong. Maybe you\'re right.',
        'But understanding WHY they see it differently...',
        '...changes everything about how you respond.',
        'Everyone is fighting a battle you know nothing about.',
      ],
      closingText: "Understanding doesn't mean agreeing. It means seeing.",
      style: 'grounding',
      nextStepId: 'response-choice',
    },
    {
      id: 'response-choice',
      type: 'choice',
      instruction: 'How will you use this understanding?',
      question: 'What feels right for this conflict?',
      options: [
        {
          id: 'reach-out',
          label: 'Reach out with understanding',
          subtext: "I'll listen first in our next conversation",
          nextStepId: 'reach-affirmation',
          storeAs: 'empathyAction',
        },
        {
          id: 'release',
          label: 'Release the need to be right',
          subtext: "Understanding is more important than winning",
          nextStepId: 'release-affirmation',
          storeAs: 'empathyAction',
        },
      ],
    },
    {
      id: 'reach-affirmation',
      type: 'affirmation',
      preText: "You chose connection over being right.",
      statement: "In my next conversation with this person, I will listen to understand — not to respond. Their perspective matters, even when I disagree.",
      confirmLabel: "I will listen first",
      style: 'commitment',
      nextStepId: 'reflection',
    },
    {
      id: 'release-affirmation',
      type: 'affirmation',
      preText: "You chose understanding over victory.",
      statement: "I release the need to be right in this conflict. Understanding this person matters more than winning the argument.",
      confirmLabel: "I choose understanding",
      style: 'gratitude',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "How did it feel to genuinely try to understand someone you've been in conflict with? What shifted?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Marcus Aurelius wrote: 'Begin each day by telling yourself: Today I will meet with interference, ingratitude, insolence... all due to ignorance.'\n\nHe didn't mean this cruelly. He meant: people act from their understanding, not yours. When you see their actions through the lens of their experience, anger transforms into compassion.",
      source: 'Marcus Aurelius & Stephen Covey',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "The greatest gift you can give another person is to make them feel truly seen. Today you practiced the art of seeing. This changes relationships more than any argument ever could.",
        ],
        byChoice: {
          'reach-out': [
            "You chose to lead with listening. When you do this, something magical happens: the other person's walls come down. Not because you agreed with them, but because they felt heard. That's the shift that transforms conflict into connection.",
          ],
          release: [
            "You released the need to be right. In a world where everyone fights to win, choosing understanding is a radical act of strength. The argument may continue, but you've already won — because you chose the relationship over the victory.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 15: FORGIVENESS IS FREEDOM
// ─────────────────────────────────────────────────────────────────────────────

const lesson15_ForgivenessFreedm: FlexibleLesson = {
  id: 'modern-15-forgiveness-freedom',
  slug: 'forgiveness-freedom',
  order: 5,
  title: 'Forgiveness is Freedom',
  subtitle: 'Letting go of resentment',
  description: "The hardest practice that offers the greatest freedom. Forgiveness isn't for them — it's for you.",
  coreConceptTag: 'forgiveness',
  xpReward: 25,
  estimatedMinutes: 7,
  thumbnail: { icon: '🕊️', color: '#22c55e' },
  teaserText: "Tomorrow you'll explore the hardest practice of all - and understand why forgiveness is freedom for YOU, not absolution for them.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Someone hurt you. Maybe recently, maybe years ago. You carry it still — a weight that follows you, a grudge that costs you energy every day.\n\nHere's the hard truth: unforgiveness is like drinking poison and expecting the other person to die.",
      subtext: "The prisoner of resentment is always you.",
      continueLabel: "I'm ready to explore this",
      mood: 'tension',
      nextStepId: 'resentment-check',
    },
    {
      id: 'resentment-check',
      type: 'resonanceCheck',
      prompt: "What kind of wound are you carrying?",
      instruction: "Tap what resonates — be honest with yourself",
      options: [
        { id: 'betrayal', text: 'Betrayal by someone I trusted' },
        { id: 'rejection', text: 'Painful rejection' },
        { id: 'abandonment', text: 'Being abandoned or left behind' },
        { id: 'unfairness', text: 'Deep unfairness' },
        { id: 'broken-promise', text: 'A broken promise' },
        { id: 'cruelty', text: 'Intentional cruelty' },
        { id: 'neglect', text: 'Being overlooked or neglected' },
        { id: 'self', text: "Something I haven't forgiven myself for" },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'wound-type',
      nextStepId: 'resentment-scale',
    },
    {
      id: 'resentment-scale',
      type: 'scaleRating',
      prompt: "How heavy does this resentment feel?",
      lowLabel: 'A distant ache',
      highLabel: 'A daily burden',
      steps: 5,
      storeAs: 'resentment-weight',
      responsesByRange: {
        low: "Even distant aches drain energy. Let's see if today is the day to finally release it.",
        mid: "It comes and goes, but it's always there. That's energy you could use for living.",
        high: "You've been carrying this boulder for too long. Not because you chose to, but because no one showed you how to put it down.",
      },
      nextStepId: 'core-insight',
    },
    {
      id: 'core-insight',
      type: 'insight',
      text: "Forgiveness is not condoning what happened. It's not pretending it didn't hurt. It's not reconciliation or trust.\n\nForgiveness is a decision to stop letting the past control your present. It's freedom for YOU, not absolution for them.",
      style: 'principle',
      followUp: "You don't have to forgive today. But you deserve to understand what forgiveness actually is — and what it isn't.",
      nextStepId: 'release-tapflow',
    },
    {
      id: 'release-tapflow',
      type: 'tapFlow',
      title: 'The Release',
      instructions: [
        'Imagine the person who hurt you standing before you.',
        'See the cord of resentment connecting you to them.',
        'This cord costs you energy every single day.',
        "You didn't create the hurt. But you're choosing to carry it.",
        'Now imagine slowly releasing that cord.',
        'Not for them. For you.',
        "The cord dissolves. You are lighter than you've been in years.",
        'Forgiveness is not a gift to them.',
        'It is a gift to yourself.',
      ],
      closingText: "The prisoner of resentment is always the one holding the key.",
      style: 'grounding',
      nextStepId: 'forgiveness-choice',
    },
    {
      id: 'forgiveness-choice',
      type: 'choice',
      instruction: 'Be honest with yourself',
      question: 'How do you feel about forgiveness right now?',
      options: [
        {
          id: 'ready',
          label: "I'm ready to choose forgiveness",
          subtext: "Not for them — for my own freedom",
          nextStepId: 'ready-affirmation',
          storeAs: 'forgivenessReady',
        },
        {
          id: 'not-ready',
          label: "I'm not ready yet — and that's honest",
          subtext: "This wound needs more time",
          nextStepId: 'not-ready-insight',
          storeAs: 'forgivenessReady',
        },
      ],
    },
    {
      id: 'ready-affirmation',
      type: 'affirmation',
      preText: "You chose freedom over resentment.",
      statement: "I release this person from the prison of my resentment. Not because they deserve it, but because I deserve peace. I choose freedom.",
      confirmLabel: "I choose freedom",
      style: 'gratitude',
      nextStepId: 'reflection',
    },
    {
      id: 'not-ready-insight',
      type: 'insight',
      text: "Forgiveness can't be forced. The fact that you're here, considering it, is progress. Some wounds need more time. The seed is planted. It will grow when you're ready.\n\nHonesty about where you are is itself a form of healing.",
      style: 'reframe',
      nextStepId: 'not-ready-affirmation',
    },
    {
      id: 'not-ready-affirmation',
      type: 'affirmation',
      preText: "You were honest. That matters.",
      statement: "I'm not ready to forgive yet. But I'm open to the possibility. That openness is the beginning.",
      confirmLabel: "I'm open to freedom",
      style: 'gratitude',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What would your life look like without this resentment? What energy would be freed if you truly let this go?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Nelson Mandela forgave 27 years of imprisonment. He said: 'Resentment is like drinking poison and then hoping it will kill your enemies.'\n\nToday you moved toward freedom — whether by choosing forgiveness or by honestly naming that you're not ready yet. Both are acts of courage.",
      source: 'Nelson Mandela',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Forgiveness is the final freedom. Not because they deserve it, but because you do. Whatever you experienced today, you moved toward the light.",
        ],
        byChoice: {
          ready: [
            "You chose freedom. The choice to forgive may need to be made again tomorrow, and the day after. It's a practice, not a moment. But today you started the journey — and that changes everything.",
          ],
          'not-ready': [
            "Honesty is always honored here. Forced forgiveness is just suppression in disguise. Keep working these practices. The day will come when you're ready — and when it does, the release will be complete.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// ASSEMBLE CHAPTER 3: RELATIONSHIPS
// ─────────────────────────────────────────────────────────────────────────────

export const chapter3_Relationships: FlexibleChapter = {
  id: 'chapter-modern-relationships',
  slug: 'relationships',
  name: 'Relationships',
  subtitle: 'The art of human connection',
  description: 'Five powerful practices for deeper connections. Learn to set boundaries, communicate honestly, and transform conflict into understanding.',
  order: 3,
  iconName: 'Heart',
  lessons: [
    lesson11_MirrorEffect,
    lesson12_RadicalHonesty,
    lesson13_BoundariesGrace,
    lesson14_EmpathyShift,
    lesson15_ForgivenessFreedm,
  ],
};

export default chapter3_Relationships;
