// ═══════════════════════════════════════════════════════════════════════════
// CHAPTER 2: RESILIENCE - Becoming Unbreakable
// ═══════════════════════════════════════════════════════════════════════════

import type { FlexibleLesson, FlexibleChapter, LessonStep } from '@/types/lessons';

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 6: THE COMEBACK FORMULA
// ─────────────────────────────────────────────────────────────────────────────

const lesson6_ComebackFormula: FlexibleLesson = {
  id: 'modern-6-comeback-formula',
  slug: 'comeback-formula',
  order: 1,
  title: 'The Comeback Formula',
  subtitle: 'Turn any setback into a setup',
  description: 'Learn the 3-step process that transforms failures into fuel.',
  coreConceptTag: 'resilience',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '🔄', color: '#ec4899' },
  teaserText: "Tomorrow you'll learn the 3-step formula that turned Michael Jordan's greatest failure into his greatest strength.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Something didn't go the way you wanted. Maybe recently. Maybe the sting is still fresh. A rejection. A failure. A door that slammed shut when you were sure it would open.",
      subtext: "Every comeback story starts with a setback.",
      continueLabel: "I have one in mind",
      mood: 'tension',
      nextStepId: 'scenario-2',
    },
    {
      id: 'scenario-2',
      type: 'scenario',
      narrative: "Michael Jordan was cut from his high school basketball team. Oprah was fired from her first TV job. Steve Jobs was ousted from the company he built.\n\nTheir setbacks weren't detours. They were launchpads.",
      bridgeQuestion: "What if your setback is a launchpad too?",
      continueLabel: "Let's find out",
      mood: 'curiosity',
      nextStepId: 'setback-check',
    },
    {
      id: 'setback-check',
      type: 'resonanceCheck',
      prompt: "What kind of setback are you carrying?",
      instruction: "Tap what resonates most",
      options: [
        { id: 'rejection', text: 'Rejection — someone said no' },
        { id: 'failure', text: 'Failure — I tried and it didn\'t work' },
        { id: 'loss', text: 'Loss — something I had is gone' },
        { id: 'betrayal', text: 'Betrayal — someone let me down' },
        { id: 'missed', text: 'Missed opportunity — I didn\'t act in time' },
        { id: 'mistake', text: 'Mistake — I messed up' },
      ],
      minSelections: 1,
      maxSelections: 2,
      storeAs: 'setback-type',
      nextStepId: 'pain-scale',
    },
    {
      id: 'pain-scale',
      type: 'scaleRating',
      prompt: "How much does this setback still sting?",
      lowLabel: 'A dull ache',
      highLabel: 'Still raw',
      steps: 5,
      storeAs: 'pain-level',
      responsesByRange: {
        low: "Even faded pain carries lessons. Let's extract them.",
        mid: "You're in the space between hurt and healing. That's where comebacks are forged.",
        high: "The rawness means it matters to you. That passion is the fuel for your comeback.",
      },
      nextStepId: 'step-one',
    },
    {
      id: 'step-one',
      type: 'insight',
      text: "STEP 1: FEEL IT FULLY.\n\nMost people either suppress their pain or drown in it. The comeback demands a third way: feel it completely, then move forward. Suppressed emotions become invisible chains. Processed emotions become fuel.",
      style: 'principle',
      followUp: "You've named it. You've felt it. That's step one — done.",
      nextStepId: 'step-two',
    },
    {
      id: 'step-two',
      type: 'insight',
      text: "STEP 2: EXTRACT THE LESSON.\n\nEvery setback contains a hidden curriculum. The question isn't 'Why did this happen TO me?' It's 'What is this teaching me FOR my future?'",
      style: 'principle',
      nextStepId: 'lesson-check',
    },
    {
      id: 'lesson-check',
      type: 'resonanceCheck',
      prompt: "What is this setback teaching you?",
      instruction: "Tap the lessons you can see",
      options: [
        { id: 'resilience', text: "I'm stronger than I thought" },
        { id: 'clarity', text: "Now I know what I really want" },
        { id: 'humility', text: "I needed to be humbled" },
        { id: 'preparation', text: "I wasn't prepared enough" },
        { id: 'wrong-path', text: "I was on the wrong path" },
        { id: 'people', text: "I learned who's really there for me" },
        { id: 'patience', text: "Good things take longer than I expected" },
        { id: 'self-worth', text: "My worth isn't defined by this outcome" },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'setback-lessons',
      nextStepId: 'step-three',
    },
    {
      id: 'step-three',
      type: 'insight',
      text: "STEP 3: DECLARE YOUR COMEBACK.\n\nA comeback isn't passive. It's a deliberate act of rising. You must name what you will do next — the specific intention that transforms victim into victor.",
      style: 'revelation',
      nextStepId: 'comeback-choice',
    },
    {
      id: 'comeback-choice',
      type: 'choice',
      instruction: 'How will you rise?',
      question: 'What does your comeback look like?',
      options: [
        {
          id: 'fight-back',
          label: 'Try again — harder and smarter',
          subtext: 'Same goal, better approach',
          nextStepId: 'fight-affirmation',
          storeAs: 'comebackStyle',
        },
        {
          id: 'adapt',
          label: 'Redirect — use this as a pivot',
          subtext: 'New direction, same fire',
          nextStepId: 'adapt-affirmation',
          storeAs: 'comebackStyle',
        },
      ],
    },
    {
      id: 'fight-affirmation',
      type: 'affirmation',
      preText: "You're not done. Not even close.",
      statement: "This setback did not break me. It revealed what I'm made of. I will try again — harder and smarter.",
      confirmLabel: "This is my comeback",
      style: 'strength',
      nextStepId: 'comeback-tapflow',
    },
    {
      id: 'adapt-affirmation',
      type: 'affirmation',
      preText: "The path changed, but the fire didn't.",
      statement: "This setback didn't end my journey. It redirected it. I will use this pain as fuel for a new direction.",
      confirmLabel: "This is my comeback",
      style: 'strength',
      nextStepId: 'comeback-tapflow',
    },
    {
      id: 'comeback-tapflow',
      type: 'tapFlow',
      title: 'The Comeback Mindset',
      instructions: [
        'You named the setback.',
        'You felt the pain without running from it.',
        'You extracted the lesson hiding inside.',
        'You declared how you will rise.',
        'This is the formula. Feel. Learn. Rise.',
        'Every legend was once a failure.',
        'Every champion was once humiliated.',
        'The only difference? They got back up.',
        'Today, you got back up.',
      ],
      closingText: "The comeback is always stronger than the setback.",
      style: 'fearless',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "How does it feel to have a comeback plan? What shifted in you during this process?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Michael Jordan said: 'I've missed more than 9,000 shots. I've lost almost 300 games. 26 times I've been trusted to take the game-winning shot and missed. I've failed over and over and over again in my life. And that is why I succeed.'\n\nYour setback is not your story. Your comeback is.",
      source: 'Michael Jordan',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "You just did what every legend does after falling: you got back up with a plan. Feel. Learn. Rise. That's the formula. The setback happened — but the comeback starts now.",
        ],
        byChoice: {
          'fight-back': [
            "You chose to try again. Not blindly — but with the lessons you just extracted. You're not the same person who failed before. You're smarter, tougher, and more aware. That's a dangerous combination.",
          ],
          adapt: [
            "You chose to pivot. That's not giving up — it's evolving. The smartest species on earth didn't survive by being the strongest. They survived by adapting. You just proved you can too.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 7: EMBRACE THE STRUGGLE
// ─────────────────────────────────────────────────────────────────────────────

const lesson7_EmbraceStruggle: FlexibleLesson = {
  id: 'modern-7-embrace-struggle',
  slug: 'embrace-struggle',
  order: 2,
  title: 'Embrace the Struggle',
  subtitle: 'Why comfort is the enemy of growth',
  description: 'Discover why voluntary hardship builds unshakeable strength.',
  coreConceptTag: 'discomfort',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '💪', color: '#8b5cf6' },
  teaserText: "Tomorrow you'll learn why the Navy SEALs, Spartans, and Stoics all embraced voluntary discomfort - and why you should too.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You have a choice in life: seek comfort now and struggle later, or embrace struggle now and earn peace later.\n\nThe paradox is this — the more you avoid discomfort, the more it controls you. The more you seek comfort, the more fragile you become.",
      subtext: "The path to becoming unbreakable runs through voluntary hardship.",
      continueLabel: "I'm ready to understand",
      mood: 'curiosity',
      nextStepId: 'comfort-check',
    },
    {
      id: 'comfort-check',
      type: 'resonanceCheck',
      prompt: "Where does comfort have a grip on you?",
      instruction: "Be honest — tap what applies",
      options: [
        { id: 'snooze', text: 'I hit snooze instead of getting up' },
        { id: 'avoid', text: 'I avoid hard conversations' },
        { id: 'scroll', text: 'I scroll instead of doing what matters' },
        { id: 'easy', text: 'I choose the easy option over the right one' },
        { id: 'procrastinate', text: 'I procrastinate on things that scare me' },
        { id: 'numb', text: 'I numb myself to avoid feeling' },
        { id: 'comfort-food', text: 'I eat/drink for comfort, not health' },
        { id: 'growth', text: 'I stay in situations I\'ve outgrown' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'comfort-zones',
      nextStepId: 'comfort-scale',
    },
    {
      id: 'comfort-scale',
      type: 'scaleRating',
      prompt: "How addicted to comfort are you?",
      lowLabel: 'I push myself often',
      highLabel: 'Comfort runs my life',
      steps: 5,
      storeAs: 'comfort-level',
      responsesByRange: {
        low: "You already embrace some discomfort. Today we sharpen that edge.",
        mid: "You're in the middle — sometimes brave, sometimes comfortable. Let's tip the scale.",
        high: "Comfort has been your prison disguised as a refuge. Today, you start breaking free.",
      },
      nextStepId: 'core-insight',
    },
    {
      id: 'core-insight',
      type: 'insight',
      text: "What you don't use, you lose. Muscles that aren't challenged atrophy. A mind that's never tested becomes fragile.\n\nThe Spartans, the Stoics, the Navy SEALs — all knew that voluntary discomfort is the vaccine against being broken by involuntary hardship.",
      source: 'David Goggins & Stoic Philosophy',
      style: 'principle',
      followUp: "David Goggins calls this 'callousing the mind.' Every time you choose hard over easy, you build mental calluses that protect you when life gets truly difficult.",
      nextStepId: 'challenge-choice',
    },
    {
      id: 'challenge-choice',
      type: 'choice',
      instruction: 'Choose your challenge',
      question: 'Which type of voluntary discomfort resonates with you?',
      options: [
        {
          id: 'physical',
          label: 'Physical challenge',
          subtext: 'Cold water, movement, endurance',
          nextStepId: 'physical-tapflow',
          storeAs: 'challengeType',
        },
        {
          id: 'mental',
          label: 'Mental challenge',
          subtext: 'Silence, stillness, delayed gratification',
          nextStepId: 'mental-tapflow',
          storeAs: 'challengeType',
        },
      ],
    },
    {
      id: 'physical-tapflow',
      type: 'tapFlow',
      title: 'The Physical Edge',
      instructions: [
        'Your body is designed for challenge, not comfort.',
        'Cold water. Hard workouts. Physical discomfort chosen voluntarily.',
        'When you splash cold water on your face, something shifts.',
        'Your nervous system wakes up. Your mind sharpens.',
        'The small act of choosing hard when easy is available...',
        '...rewires who you are at a fundamental level.',
        'Athletes know this. Warriors know this.',
        'Discomfort chosen is discomfort transformed into power.',
        'Today, choose one physical challenge. Just one.',
      ],
      closingText: "The body leads. The mind follows.",
      style: 'fearless',
      nextStepId: 'affirmation',
    },
    {
      id: 'mental-tapflow',
      type: 'tapFlow',
      title: 'The Mental Edge',
      instructions: [
        'Sit in silence. No phone. No music. No distraction.',
        'This is harder than it sounds.',
        'Your mind will resist. It will beg for stimulation.',
        'But in that resistance, something beautiful happens.',
        'You discover you can sit with discomfort.',
        'You discover you don\'t need to be entertained every second.',
        'You discover that boredom isn\'t dangerous.',
        'Stillness is where strength is forged.',
        'The person who can sit with nothing fears nothing.',
      ],
      closingText: "Silence is the ultimate modern challenge.",
      style: 'grounding',
      nextStepId: 'affirmation',
    },
    {
      id: 'affirmation',
      type: 'affirmation',
      preText: "You chose the hard thing. That's rare.",
      statement: "I am someone who voluntarily does hard things. Comfort is not my master. Challenge is my teacher.",
      confirmLabel: "I embrace the struggle",
      style: 'strength',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What did you notice during the challenge? How did it feel to voluntarily choose something hard?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "David Goggins went from 300 pounds and depressed to becoming a Navy SEAL, Army Ranger, and ultramarathon runner.\n\nHis secret? 'You have to build calluses on your brain just like how you build calluses on your hands. It's the voluntary suffering that makes you what you are.'",
      source: 'David Goggins',
      sourceBook: "Can't Hurt Me",
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "The person who voluntarily does hard things doesn't fear involuntary hardship. You just became a little more unbreakable.",
        ],
        byChoice: {
          physical: [
            "Physical challenges are the gateway to mental toughness. The body leads, the mind follows. Cold showers, hard workouts, physical discomfort — these are the training ground for an unbreakable spirit.",
          ],
          mental: [
            "Silence is the ultimate modern challenge. In a world of endless stimulation, the ability to sit with yourself is a superpower. You just practiced what most people run from.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 8: FEAR-SETTING
// ─────────────────────────────────────────────────────────────────────────────

const lesson8_FearSetting: FlexibleLesson = {
  id: 'modern-8-fear-setting',
  slug: 'fear-setting',
  order: 3,
  title: 'Fear-Setting',
  subtitle: "Tim Ferriss's antidote to paralysis",
  description: 'Define your fears to disarm them. A powerful exercise for making hard decisions.',
  coreConceptTag: 'fear',
  xpReward: 24,
  estimatedMinutes: 7,
  thumbnail: { icon: '🎯', color: '#ef4444' },
  teaserText: "Tomorrow you'll learn the fear-dissolving technique that Tim Ferriss credits with saving his life.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "There's something you've been avoiding. A decision you keep postponing. A leap you're afraid to take. The unknown feels dangerous, so you stay stuck.\n\nBut what if the REAL danger is inaction?",
      subtext: "Clear seeing defeats unseen fears.",
      continueLabel: "I know what it is",
      mood: 'tension',
      nextStepId: 'fear-check',
    },
    {
      id: 'fear-check',
      type: 'resonanceCheck',
      prompt: "What type of fear is keeping you stuck?",
      instruction: "Tap what resonates",
      options: [
        { id: 'failure', text: 'Fear of failing publicly' },
        { id: 'rejection', text: 'Fear of being rejected' },
        { id: 'money', text: 'Fear of financial loss' },
        { id: 'judgment', text: 'Fear of being judged' },
        { id: 'unknown', text: 'Fear of the unknown' },
        { id: 'change', text: 'Fear of change itself' },
        { id: 'success', text: 'Fear of actually succeeding' },
        { id: 'regret', text: 'Fear of making the wrong choice' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'fear-types',
      nextStepId: 'fear-scale',
    },
    {
      id: 'fear-scale',
      type: 'scaleRating',
      prompt: "How paralyzed are you by this fear?",
      lowLabel: 'Slightly hesitant',
      highLabel: 'Completely stuck',
      steps: 5,
      storeAs: 'paralysis-level',
      responsesByRange: {
        low: "A small fear can still block big moves. Let's disarm it.",
        mid: "You're in the fog. What we're about to do cuts through fog like nothing else.",
        high: "The more paralyzed you are, the more powerful this exercise will be. Stay with me.",
      },
      nextStepId: 'ferriss-intro',
    },
    {
      id: 'ferriss-intro',
      type: 'insight',
      text: "Tim Ferriss developed 'Fear-Setting' after nearly taking his own life. He realized: we rarely define our fears in detail. The undefined stays terrifying. The defined becomes manageable.\n\nThe process has three steps: Define. Prevent. Repair.",
      source: 'Tim Ferriss',
      sourceBook: 'The 4-Hour Workweek',
      style: 'principle',
      nextStepId: 'define-tapflow',
    },
    {
      id: 'define-tapflow',
      type: 'tapFlow',
      title: 'Define the Worst Case',
      instructions: [
        'Think of the thing you\'ve been avoiding.',
        'Now imagine the absolute WORST that could happen if you did it.',
        'Not the likely outcome. The worst possible scenario.',
        'You take the leap and... what? Spell it out in your mind.',
        'Maybe you lose money. Maybe you\'re embarrassed.',
        'Maybe someone says no. Maybe you fail publicly.',
        'See it clearly. Feel it. Don\'t flinch.',
        'Good. You just looked your fear in the eye.',
        'Now here\'s what changes everything...',
      ],
      style: 'fearless',
      nextStepId: 'prevent-insight',
    },
    {
      id: 'prevent-insight',
      type: 'insight',
      text: "PREVENT: What could you do to reduce the probability of the worst case? Safety nets. Preparation. Small tests before big leaps.\n\nREPAIR: If the worst DID happen, what would you do to recover? You've recovered from hard things before. You'd recover from this too.",
      style: 'reframe',
      followUp: "Now the crucial flip...",
      nextStepId: 'cost-insight',
    },
    {
      id: 'cost-insight',
      type: 'insight',
      text: "What is the COST of inaction?\n\nIf you don't take this leap in 6 months, 1 year, 3 years — what will your life look like? The real risk isn't failure. It's never trying. It's the slow death of playing it safe.",
      style: 'revelation',
      nextStepId: 'action-choice',
    },
    {
      id: 'action-choice',
      type: 'choice',
      instruction: 'Now that you can see clearly',
      question: 'Is the cost of inaction greater than the risk of action?',
      options: [
        {
          id: 'yes-act',
          label: 'Yes — inaction costs more than the risk',
          subtext: "I'd rather fail trying than succeed at nothing",
          nextStepId: 'act-affirmation',
          storeAs: 'fearDecision',
        },
        {
          id: 'need-time',
          label: "I need more time to prepare",
          subtext: "But I won't let this become permanent avoidance",
          nextStepId: 'prepare-affirmation',
          storeAs: 'fearDecision',
        },
      ],
    },
    {
      id: 'act-affirmation',
      type: 'affirmation',
      preText: "You looked fear in the eye. It blinked first.",
      statement: "I choose action over avoidance. The cost of standing still is greater than the risk of moving forward.",
      confirmLabel: "I choose to act",
      style: 'strength',
      nextStepId: 'reflection',
    },
    {
      id: 'prepare-affirmation',
      type: 'affirmation',
      preText: "Preparation is not avoidance — if you set a deadline.",
      statement: "I will prepare and act within a clear timeframe. This fear will not own me permanently.",
      confirmLabel: "I will move forward",
      style: 'commitment',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What is the true cost of NOT taking this action? What will you regret if you stay stuck?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Tim Ferriss says: 'What we fear doing most is usually what we most need to do. A person's success in life can usually be measured by the number of uncomfortable conversations he or she is willing to have.'\n\nYou've done the hard work of clarity. The fear didn't disappear — but it became manageable. That's the point.",
      source: 'Tim Ferriss',
      sourceBook: 'The 4-Hour Workweek',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "You just did what Tim Ferriss credits with saving his life. By defining the fear, you took away its power. Most people never look their fears in the eye. You just did.",
        ],
        byChoice: {
          'yes-act': [
            "You chose action. The fear is still there — but you're moving anyway. That's not fearlessness. That's courage. And courage is the only thing that changes lives.",
          ],
          'need-time': [
            "You chose preparation over panic. That's wise — as long as 'not yet' doesn't become 'never.' Set your deadline. Mark it. And when it comes, remember this moment of clarity.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 9: THE ANTIFRAGILE MIND
// ─────────────────────────────────────────────────────────────────────────────

const lesson9_AntifragileMind: FlexibleLesson = {
  id: 'modern-9-antifragile-mind',
  slug: 'antifragile-mind',
  order: 4,
  title: 'The Antifragile Mind',
  subtitle: 'How to grow from chaos',
  description: "Based on Nassim Taleb's concept: become someone who gains from disorder.",
  coreConceptTag: 'antifragile',
  xpReward: 22,
  estimatedMinutes: 5,
  thumbnail: { icon: '⚡', color: '#3b82f6' },
  teaserText: "Tomorrow you'll discover why some people get STRONGER from chaos while others break - and how to become the former.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Some things break under stress. Glass. Porcelain. A fragile ego.\n\nSome things survive stress. Rocks. Concrete. A resilient person.\n\nBut a rare few actually get STRONGER when stressed. Muscles. Immune systems. And — if you let it — your mind.",
      subtext: "Beyond resilience lies antifragility.",
      continueLabel: "Tell me more",
      mood: 'curiosity',
      nextStepId: 'stress-check',
    },
    {
      id: 'stress-check',
      type: 'resonanceCheck',
      prompt: "What's stressing you right now?",
      instruction: "Tap your current stressors",
      options: [
        { id: 'work', text: 'Work or career pressure' },
        { id: 'money', text: 'Financial stress' },
        { id: 'relationship', text: 'Relationship tension' },
        { id: 'health', text: 'Health concerns' },
        { id: 'uncertainty', text: 'Uncertainty about the future' },
        { id: 'overload', text: 'Too many responsibilities' },
        { id: 'conflict', text: 'Conflict with someone' },
        { id: 'self', text: 'Pressure I put on myself' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'current-stressors',
      nextStepId: 'stress-scale',
    },
    {
      id: 'stress-scale',
      type: 'scaleRating',
      prompt: "How do you typically respond to stress?",
      lowLabel: 'I crumble',
      highLabel: 'I rise to it',
      steps: 5,
      storeAs: 'stress-response',
      responsesByRange: {
        low: "You've been fragile under pressure. That's about to change.",
        mid: "You survive stress, but you don't grow from it. There's a level beyond survival.",
        high: "You already have antifragile instincts. Let's make them conscious and deliberate.",
      },
      nextStepId: 'core-insight',
    },
    {
      id: 'core-insight',
      type: 'insight',
      text: "Nassim Taleb coined 'antifragile' to describe things that gain from disorder. The opposite of fragile isn't robust — robust just survives.\n\nThe opposite of fragile is antifragile: it IMPROVES from stressors, shocks, and volatility.",
      source: 'Nassim Taleb',
      sourceBook: 'Antifragile',
      style: 'principle',
      followUp: "Wind extinguishes a candle but energizes fire. You're learning to be the fire, not the candle.",
      nextStepId: 'reframe-tapflow',
    },
    {
      id: 'reframe-tapflow',
      type: 'tapFlow',
      title: 'Becoming Antifragile',
      instructions: [
        'Think of the stressor you named.',
        "Now imagine you're not just surviving it...",
        "...you're actually getting stronger because of it.",
        'What skill is this forcing you to develop?',
        'What weakness is it exposing for you to fix?',
        'What would it mean to THANK this stressor?',
        'Not for the pain. But for what it\'s building.',
        'Muscles grow from resistance. So does character.',
        'You are not fragile. You are antifragile.',
      ],
      style: 'fearless',
      nextStepId: 'growth-check',
    },
    {
      id: 'growth-check',
      type: 'resonanceCheck',
      prompt: "How could this stress be making you stronger?",
      instruction: "Tap what resonates",
      options: [
        { id: 'patience', text: "It's teaching me patience" },
        { id: 'boundaries', text: "It's forcing me to set boundaries" },
        { id: 'creativity', text: "It's making me more creative" },
        { id: 'priorities', text: "It's clarifying my priorities" },
        { id: 'toughness', text: "It's building mental toughness" },
        { id: 'adaptability', text: "It's making me more adaptable" },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'growth-areas',
      nextStepId: 'stance-choice',
    },
    {
      id: 'stance-choice',
      type: 'choice',
      instruction: 'Choose your relationship with stress',
      question: 'Going forward, how will you approach stressors?',
      options: [
        {
          id: 'embrace',
          label: 'Embrace them — stress is my training ground',
          nextStepId: 'embrace-affirmation',
          storeAs: 'stressStance',
        },
        {
          id: 'reframe',
          label: 'Reframe them — find the growth in every challenge',
          nextStepId: 'reframe-affirmation',
          storeAs: 'stressStance',
        },
      ],
    },
    {
      id: 'embrace-affirmation',
      type: 'affirmation',
      preText: "You chose to become the fire.",
      statement: "I don't avoid stress — I grow from it. Every challenge is a rep. Every setback is training. I am antifragile.",
      confirmLabel: "I am antifragile",
      style: 'strength',
      nextStepId: 'reflection',
    },
    {
      id: 'reframe-affirmation',
      type: 'affirmation',
      preText: "You chose to see the gift in the struggle.",
      statement: "Every stressor contains a lesson. I will find it, learn from it, and become stronger because of it.",
      confirmLabel: "I grow from chaos",
      style: 'strength',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What would change if you truly believed that stress makes you stronger, not weaker?",
      minimumWords: 5,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "Taleb writes: 'Wind extinguishes a candle and energizes fire. Likewise with randomness, uncertainty, chaos: you want to use them, not hide from them.'\n\nThe antifragile don't fear volatility — they need it to grow. You just practiced seeing stress as fertilizer, not poison.",
      source: 'Nassim Taleb',
      sourceBook: 'Antifragile',
      style: 'quote',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Most people spend their lives trying to eliminate stress. The antifragile spend theirs learning to gain from it. You're joining their ranks.",
        ],
        byChoice: {
          embrace: [
            "You chose to make stress your training ground. That's the antifragile mindset in its purest form. The next time chaos arrives, you'll welcome it — because you know it's making you stronger.",
          ],
          reframe: [
            "You chose to find the growth in every challenge. That's a powerful shift. You won't be able to unsee it now — every stressor will carry a hidden curriculum, and you'll be the student who shows up.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 10: LETTER TO YOUR FUTURE SELF
// ─────────────────────────────────────────────────────────────────────────────

const lesson10_FutureSelf: FlexibleLesson = {
  id: 'modern-10-future-self',
  slug: 'future-self',
  order: 5,
  title: 'Letter to Your Future Self',
  subtitle: 'Bridge the gap between who you are and who you will become',
  description: 'A powerful visualization and writing exercise that clarifies your trajectory.',
  coreConceptTag: 'vision',
  xpReward: 25,
  estimatedMinutes: 7,
  thumbnail: { icon: '✉️', color: '#14b8a6' },
  teaserText: "Tomorrow you'll write a letter to yourself one year from now - a powerful practice that bridges present and future.",
  exercises: [],
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "One year from today, a future version of you exists. They have lived through everything that's coming. They know which decisions mattered, which fears were overblown, and what truly changed their life.",
      subtext: "What if you could receive a letter from that person?",
      continueLabel: "I want to hear from them",
      mood: 'hope',
      nextStepId: 'future-tapflow',
    },
    {
      id: 'future-tapflow',
      type: 'tapFlow',
      title: 'Meet Your Future Self',
      instructions: [
        'Breathe deeply. Let yourself settle.',
        "It's one year from today.",
        'Imagine the best realistic version of yourself.',
        'What habits did they build?',
        'What fear did they overcome?',
        'What relationship did they strengthen?',
        'What are they most proud of?',
        'See them clearly. They are waiting to speak to you.',
      ],
      closingText: "Your future self is shaped by decisions you make today.",
      style: 'cosmic',
      nextStepId: 'hope-check',
    },
    {
      id: 'hope-check',
      type: 'resonanceCheck',
      prompt: "What do you hope your future self has accomplished?",
      instruction: "Tap your deepest hopes",
      options: [
        { id: 'health', text: 'Better physical health' },
        { id: 'peace', text: 'More inner peace' },
        { id: 'career', text: 'Career growth or change' },
        { id: 'relationships', text: 'Deeper relationships' },
        { id: 'confidence', text: 'More self-confidence' },
        { id: 'creativity', text: 'Creative expression' },
        { id: 'freedom', text: 'Financial freedom' },
        { id: 'purpose', text: 'A clear sense of purpose' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'future-hopes',
      nextStepId: 'bridge-insight',
    },
    {
      id: 'bridge-insight',
      type: 'insight',
      text: "Research shows that people who feel connected to their future self make better decisions RIGHT NOW. The more vivid your future self becomes, the more you act in their interest.\n\nYour future self isn't a stranger. They're you — shaped by the choices you make starting today.",
      style: 'principle',
      followUp: "Now let's reverse it. Instead of receiving a letter, you'll WRITE one TO your future self.",
      nextStepId: 'letter-scale',
    },
    {
      id: 'letter-scale',
      type: 'scaleRating',
      prompt: "How connected do you feel to who you'll be in a year?",
      lowLabel: 'Like a stranger',
      highLabel: 'Like me, but better',
      steps: 5,
      storeAs: 'future-connection',
      responsesByRange: {
        low: "That's normal. Most people can't picture their future self. This exercise bridges that gap.",
        mid: "You can see the outline. This exercise will sharpen the image.",
        high: "You already feel the connection. This letter will make it unbreakable.",
      },
      nextStepId: 'letter-choice',
    },
    {
      id: 'letter-choice',
      type: 'choice',
      instruction: 'What matters most to tell your future self?',
      question: 'What kind of letter do you want to write?',
      options: [
        {
          id: 'promise',
          label: 'A promise — what I commit to becoming',
          nextStepId: 'promise-affirmation',
          storeAs: 'letterType',
        },
        {
          id: 'reminder',
          label: 'A reminder — what I want to never forget',
          nextStepId: 'reminder-affirmation',
          storeAs: 'letterType',
        },
      ],
    },
    {
      id: 'promise-affirmation',
      type: 'affirmation',
      preText: "A promise from your present self to your future self.",
      statement: "I promise to make decisions today that serve who I'm becoming. Not who I was. Not who others want me to be. Who I choose to be.",
      confirmLabel: "This is my promise",
      style: 'commitment',
      nextStepId: 'reflection',
    },
    {
      id: 'reminder-affirmation',
      type: 'affirmation',
      preText: "A reminder from your present self to your future self.",
      statement: "Remember where you started. Remember what mattered to you right now. Remember the person who sat here and decided to grow.",
      confirmLabel: "I will remember",
      style: 'gratitude',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "Write a letter to yourself one year from now. What do you hope they've accomplished? What do you want to remind them about who you are today?",
      minimumWords: 10,
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      nextStepId: 'closing-insight',
    },
    {
      id: 'closing-insight',
      type: 'insight',
      text: "You've just done something that bridges present and future. This letter is a contract with yourself. The person you wrote to is real — they're built by decisions you make starting today.\n\nSave this letter somewhere you'll find it in a year. Reading your own words from a pivotal moment has a power nothing else can match.",
      style: 'reframe',
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "You've just built a bridge between who you are and who you're becoming. This letter is a contract with yourself. The person you wrote to is real — they're built by decisions you make starting today.",
        ],
        byChoice: {
          promise: [
            "You made a promise. Not to someone else — to yourself. Those are the hardest promises to keep, and the most important. Your future self is counting on you. Don't let them down.",
          ],
          reminder: [
            "You wrote a reminder that your future self needs to read. Because success has a way of making us forget where we started. This letter preserves the hunger, the hope, and the humanity of this moment.",
          ],
        },
      },
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// ASSEMBLE CHAPTER 2: RESILIENCE
// ─────────────────────────────────────────────────────────────────────────────

export const chapter2_Resilience: FlexibleChapter = {
  id: 'chapter-modern-resilience',
  slug: 'resilience',
  name: 'Resilience',
  subtitle: 'Becoming unbreakable',
  description: 'Five advanced practices for developing mental toughness. Learn to thrive in chaos, recover from setbacks, and become antifragile.',
  order: 2,
  iconName: 'Shield',
  lessons: [
    lesson6_ComebackFormula,
    lesson7_EmbraceStruggle,
    lesson8_FearSetting,
    lesson9_AntifragileMind,
    lesson10_FutureSelf,
  ],
};

export default chapter2_Resilience;
