import type { SparkVideo } from '@/types/spark';

// Spark video catalog — 40 videos across 6 categories.
export const sparkVideos: SparkVideo[] = [
  {
    id: 'spark_001',
    youtubeId: 'zE8iYfWjw9w',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'Build the habit. Keep the promise.',
    tags: ['discipline', 'habits'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_002',
    youtubeId: 'XnjiprcNurg',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'Rewire your standards. Raise the bar.',
    tags: ['mindset', 'standards'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_003',
    youtubeId: 'i4D_3IF35C0',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'Keep moving, even when it hurts.',
    tags: ['resilience', 'grit'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_004',
    youtubeId: '5f7E4DQG6kk',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'Cut the noise. Lock in.',
    tags: ['focus', 'clarity'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_005',
    youtubeId: 'QUIvc_FRUu4',
    category: 'calm',
    creatorName: 'Motivational',
    caption: 'Slow the breath. Steady the mind.',
    tags: ['calm', 'balance'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_006',
    youtubeId: 'tKWlYEXEJj0',
    category: 'gratitude',
    creatorName: 'Motivational',
    caption: 'Appreciate the moment. Then build.',
    tags: ['gratitude', 'perspective'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_007',
    youtubeId: '2ighMmw2l0U',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'No excuses. Just reps.',
    tags: ['discipline', 'reps'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_008',
    youtubeId: 'RAccay_S9qA',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'Think bigger. Move faster.',
    tags: ['mindset', 'action'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_009',
    youtubeId: 'KjAiwJOQFZ4',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'Take the hit. Come back stronger.',
    tags: ['resilience', 'comeback'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_010',
    youtubeId: '08UrHRDen4U',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'One target. Full effort.',
    tags: ['focus', 'execution'],
    addedAt: '2026-02-08',
  },
  {
    id: 'spark_011',
    youtubeId: 'ilC52Ukd2AA',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'Stay locked in. The grind speaks for itself.',
    tags: ['discipline', 'grind'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_012',
    youtubeId: 'itO2xxeJqgY',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'Your mind is the weapon. Sharpen it daily.',
    tags: ['mindset', 'growth'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_013',
    youtubeId: 'XSAOfJFhxlM',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'Pain is temporary. Quitting lasts forever.',
    tags: ['resilience', 'endurance'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_014',
    youtubeId: 'X30BmLLXm4w',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'Eliminate distractions. Dominate the day.',
    tags: ['focus', 'productivity'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_015',
    youtubeId: 'MC1ocuRp99k',
    category: 'calm',
    creatorName: 'Motivational',
    caption: 'Find stillness in the storm.',
    tags: ['calm', 'peace'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_016',
    youtubeId: '8sfquJvcG9E',
    category: 'gratitude',
    creatorName: 'Motivational',
    caption: 'Count the wins, not the losses.',
    tags: ['gratitude', 'wins'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_017',
    youtubeId: 'hjzR0xgZP84',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'Consistency beats talent every single time.',
    tags: ['discipline', 'consistency'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_018',
    youtubeId: '6_f-QYYbL88',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'Change the narrative. Rewrite your story.',
    tags: ['mindset', 'identity'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_019',
    youtubeId: '_uCeWsPagbo',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'Fall seven times. Stand up eight.',
    tags: ['resilience', 'perseverance'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_020',
    youtubeId: 'mtI5qcyARA8',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'Tunnel vision is a superpower.',
    tags: ['focus', 'determination'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_021',
    youtubeId: 'ipbinkCI6F0',
    category: 'calm',
    creatorName: 'Motivational',
    caption: 'Breathe deep. Let the noise fade.',
    tags: ['calm', 'breathing'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_022',
    youtubeId: 'xo-z-r4Zi-k',
    category: 'gratitude',
    creatorName: 'Motivational',
    caption: 'Be thankful for the struggle. It shapes you.',
    tags: ['gratitude', 'growth'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_023',
    youtubeId: 'Zzl_4IKrcQo',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'Do what needs to be done. No negotiation.',
    tags: ['discipline', 'commitment'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_024',
    youtubeId: 'osEBJFIg-PU',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'Believe before you see. Then prove it.',
    tags: ['mindset', 'belief'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_025',
    youtubeId: 'wN2MMenGp58',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'Scars are proof you survived.',
    tags: ['resilience', 'strength'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_026',
    youtubeId: 'duAZyER6UJs',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'Block out everything. Zero in on the goal.',
    tags: ['focus', 'goals'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_027',
    youtubeId: 'BsblgcBB17A',
    category: 'calm',
    creatorName: 'Motivational',
    caption: 'Silence the chaos. Find your center.',
    tags: ['calm', 'mindfulness'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_028',
    youtubeId: 'CPUb9kK14kk',
    category: 'gratitude',
    creatorName: 'Motivational',
    caption: 'Every day above ground is a blessing.',
    tags: ['gratitude', 'life'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_029',
    youtubeId: 'pNLy37MqXFE',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'Show up when nobody is watching.',
    tags: ['discipline', 'work ethic'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_030',
    youtubeId: 'JtPpp3Ep6nA',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'You become what you refuse to give up on.',
    tags: ['mindset', 'persistence'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_031',
    youtubeId: 'cY4dM7xno4M',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'The comeback is always stronger than the setback.',
    tags: ['resilience', 'comeback'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_032',
    youtubeId: 'abctV0Pw_s0',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'Laser focus. No distractions. Pure execution.',
    tags: ['focus', 'execution'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_033',
    youtubeId: '7tpobe-cAqI',
    category: 'calm',
    creatorName: 'Motivational',
    caption: 'Peace is not the absence of chaos. It is the mastery of it.',
    tags: ['calm', 'mastery'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_034',
    youtubeId: 'wFNtN_XTroA',
    category: 'gratitude',
    creatorName: 'Motivational',
    caption: 'Gratitude turns what you have into enough.',
    tags: ['gratitude', 'abundance'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_035',
    youtubeId: 'SgBcbRuCEJI',
    category: 'discipline',
    creatorName: 'Motivational',
    caption: 'Discipline is choosing between what you want now and what you want most.',
    tags: ['discipline', 'sacrifice'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_036',
    youtubeId: 'EXwsE35j8xA',
    category: 'mindset',
    creatorName: 'Motivational',
    caption: 'The only limits are the ones you accept.',
    tags: ['mindset', 'limitless'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_037',
    youtubeId: '-Cnf2QRnkF4',
    category: 'resilience',
    creatorName: 'Motivational',
    caption: 'Broken crayons still color.',
    tags: ['resilience', 'hope'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_038',
    youtubeId: 'SYGR9vcUjg4',
    category: 'focus',
    creatorName: 'Motivational',
    caption: 'Where attention goes, energy flows.',
    tags: ['focus', 'energy'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_039',
    youtubeId: 'uCKyZ_2M4tQ',
    category: 'calm',
    creatorName: 'Motivational',
    caption: 'Be water. Adapt. Flow. Overcome.',
    tags: ['calm', 'adaptability'],
    addedAt: '2026-02-27',
  },
  {
    id: 'spark_040',
    youtubeId: 'KCSk0_HmMsU',
    category: 'gratitude',
    creatorName: 'Motivational',
    caption: 'The present moment is the only one guaranteed.',
    tags: ['gratitude', 'presence'],
    addedAt: '2026-02-27',
  },
];

export function getShuffledSparkVideos(watchedIds: string[]): SparkVideo[] {
  const watchedSet = new Set(watchedIds);
  const unwatched = sparkVideos.filter((video) => !watchedSet.has(video.id));
  const pool = unwatched.length > 0 ? [...unwatched] : [...sparkVideos];

  for (let index = pool.length - 1; index > 0; index -= 1) {
    const randomIndex = Math.floor(Math.random() * (index + 1));
    [pool[index], pool[randomIndex]] = [pool[randomIndex], pool[index]];
  }

  return pool;
}
