// ═══════════════════════════════════════════════════════════════════════════
// CHAPTER 3: CITIZEN OF THE COSMOS - Expanding from Self to Universe
// ═══════════════════════════════════════════════════════════════════════════

import type { FlexibleLesson, FlexibleChapter, LessonStep } from '@/types/lessons';
import { stoicLesson11Exercises, stoicLesson12Exercises, stoicLesson13Exercises, stoicLesson14Exercises, stoicLesson15Exercises } from './stoicismExerciseContent';

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 11: THE VIEW FROM ABOVE
// ─────────────────────────────────────────────────────────────────────────────

const lesson11: FlexibleLesson = {
  id: 'stoic-11-view-from-above',
  slug: 'view-from-above',
  order: 1,
  title: 'The View from Above',
  subtitle: 'Zoom out. Way out.',
  description: 'Practice the ancient meditation that gave a Roman emperor peace during plague and war.',
  coreConceptTag: 'cosmic-perspective',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '🌍', color: '#4f46e5' },
  teaserText: "Tomorrow you'll practice the meditation that helped a Roman emperor find peace during plague and war.",
  exercises: stoicLesson11Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You're consumed by a problem. It fills your vision. It's all you can think about — the worry, the frustration, the weight of it pressing down on your chest.\n\nNow imagine a camera pulling back. Slowly. Your room. Your building. Your city. Your country. The planet — a pale blue dot hanging in an ocean of stars.",
      subtext: "Marcus Aurelius did this every night.",
      continueLabel: "Pull back the camera",
      mood: 'curiosity',
      nextStepId: 'ascent-tapflow',
    },
    {
      id: 'ascent-tapflow',
      type: 'tapFlow',
      title: 'The Ascent',
      instructions: [
        'You are sitting where you are. Feel the weight of your problem.',
        'Now rise. See the room around you. Walls, furniture, the small space you inhabit.',
        'Higher. Your building from above. Other lives happening in every room.',
        'Higher still. Your city spreads out below. Thousands of lives. Thousands of problems just like yours.',
        'Your country. Millions of people waking, sleeping, worrying, laughing.',
        'The Earth now. A blue marble. Every war, every love story, every triumph — on that sphere.',
        'Pull back further. The solar system. Earth is a speck beside a middling star.',
        'The stars. Billions of them. Every person who ever lived, every empire that ever rose and fell, every heartbreak and every joy — all of it happened on that tiny dot.',
      ],
      closingText: "Now look at your problem from here.",
      style: 'cosmic',
      nextStepId: 'problem-scale',
    },
    {
      id: 'problem-scale',
      type: 'scaleRating',
      prompt: 'After the ascent, how does your problem feel?',
      lowLabel: 'Just as large',
      highLabel: 'Tiny',
      steps: 5,
      storeAs: 'problem-perspective',
      responsesByRange: {
        low: "Some problems resist perspective. That's okay. The practice still plants a seed.",
        mid: "It shifted. Not gone, but loosened. That loosening is where peace begins.",
        high: "You felt it — that sudden smallness. Not of you, but of the weight you were carrying.",
      },
      nextStepId: 'view-insight',
    },
    {
      id: 'view-insight',
      type: 'insight',
      text: "This is the View from Above — one of the most powerful Stoic meditations. Marcus Aurelius practiced it constantly.\n\nHe wrote: 'Think of the whole of existence, of which your share is tiny; the whole of time, in which a brief and momentary span has been assigned to you.'\n\nThe most powerful man in the Western world, deliberately making himself small. Not to feel worthless — but to stop his problems from swallowing everything else.",
      source: 'Marcus Aurelius',
      sourceBook: 'Meditations',
      style: 'principle',
      followUp: "The View from Above doesn't dismiss your problems. It stops your problems from dismissing everything else — the beauty, the wonder, the sheer improbability of being alive at all.",
      nextStepId: 'gain-check',
    },
    {
      id: 'gain-check',
      type: 'resonanceCheck',
      prompt: 'What do you gain from cosmic perspective?',
      instruction: 'Tap what resonated',
      options: [
        { id: 'less-overwhelming', text: 'Problems feel less overwhelming' },
        { id: 'connected', text: 'Connected to something larger' },
        { id: 'ego-reduction', text: 'Reduces ego and self-importance' },
        { id: 'clarity', text: 'See what really matters' },
        { id: 'peace', text: 'A strange peace' },
        { id: 'time-precious', text: 'Time feels more precious' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'perspective-gains',
      nextStepId: 'perspective-choice',
    },
    {
      id: 'perspective-choice',
      type: 'choice',
      question: 'What hit you hardest from the ascent?',
      options: [
        {
          id: 'worries-small',
          label: 'My worries feel small',
          subtext: 'The zoom-out shrank them',
          nextStepId: 'worries-insight',
          storeAs: 'viewResponse',
        },
        {
          id: 'time-brief',
          label: 'My time is brief',
          subtext: 'I felt the shortness of it all',
          nextStepId: 'time-insight',
          storeAs: 'viewResponse',
        },
      ],
    },
    {
      id: 'worries-insight',
      type: 'insight',
      text: "Your worries shrank — but notice something important. Your capacity to respond didn't shrink with them.\n\nThat's the real gift of the View from Above. The problem gets smaller, but you stay the same size. Suddenly you're bigger than what was crushing you. You have room to breathe, room to think, room to act clearly instead of reacting desperately.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'time-insight',
      type: 'insight',
      text: "You felt the brevity. Good. The Stoics wanted you to feel it — not as despair, but as urgency.\n\nTime contracts when you zoom out. But your agency doesn't. You still get to choose how to spend every moment you have. The shortness of life doesn't reduce your power. It concentrates it. Every decision matters more, not less, because your time is finite.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What deserves less attention than you're giving it right now? And what deserves more?",
      minimumWords: 5,
      encouragements: [
        "Be specific. Name the thing that's been too big.",
        "Now name what you've been neglecting because of it.",
      ],
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Marcus Aurelius ruled an empire in crisis — plague, war, betrayal — and still found proportion. He didn't shrink from his duties. He shrank his anxiety until it fit inside his capacity to act. You just practiced the same meditation that kept an emperor sane.",
        ],
        byChoice: {
          'worries-small': [
            "Your problems are real. They deserve attention. But they don't deserve all of your attention. The View from Above gives you back the space they stole. Use that space for the things that actually matter — the people, the moments, the life happening while you worry.",
          ],
          'time-brief': [
            "Marcus wrote: 'Not to live as if you had endless years ahead of you. Death overshadows you. While you're alive and able — be good.' Your time is short. That's not sad. That's clarifying. Spend it on what deserves it.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      statement: 'I see from above. My problems are real, but the universe is vast, and so is my capacity to respond.',
      confirmLabel: 'I see from above',
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 12: THE RIVER
// ─────────────────────────────────────────────────────────────────────────────

const lesson12: FlexibleLesson = {
  id: 'stoic-12-the-river',
  slug: 'the-river',
  order: 2,
  title: 'The River',
  subtitle: 'Stop fighting the current. Become it.',
  description: 'Discover why the Stoics didn\'t just accept what happened — they loved it.',
  coreConceptTag: 'amor-fati',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '🌊', color: '#6366f1' },
  teaserText: "Tomorrow you'll learn why the Stoics didn't just accept what happened — they loved it.",
  exercises: stoicLesson12Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You're fighting something. A loss. A change. A reality you refuse to accept. You push against it with everything you have — and it doesn't move. It never moves.\n\nYou're exhausted. Not from the problem itself, but from the war you're waging against what already is.",
      subtext: "The river doesn't care that you're fighting it.",
      continueLabel: "I know this exhaustion",
      mood: 'struggle',
      nextStepId: 'reality-check',
    },
    {
      id: 'reality-check',
      type: 'resonanceCheck',
      prompt: 'What reality are you fighting?',
      instruction: 'Tap what you\'re resisting',
      options: [
        { id: 'loss', text: 'A loss I can\'t undo' },
        { id: 'change', text: 'An unwanted change' },
        { id: 'limitation', text: 'A limitation I can\'t fix' },
        { id: 'person', text: 'A person who won\'t change' },
        { id: 'aging', text: 'Aging or the passage of time' },
        { id: 'world', text: 'The way the world is' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'resistance-targets',
      nextStepId: 'resistance-scale',
    },
    {
      id: 'resistance-scale',
      type: 'scaleRating',
      prompt: 'How much energy are you spending resisting what is?',
      lowLabel: 'A little',
      highLabel: 'All of it',
      steps: 5,
      storeAs: 'resistance-energy',
      responsesByRange: {
        low: "Even a little resistance drains you. Imagine redirecting that energy toward something you can actually change.",
        mid: "You're splitting your energy — half fighting reality, half living. What if you had all of it back?",
        high: "You're pouring yourself into a war you can't win. Not because you're weak, but because the enemy is what already happened. Today, we end that war.",
      },
      nextStepId: 'amor-fati-insight',
    },
    {
      id: 'amor-fati-insight',
      type: 'insight',
      text: "The Stoics had a concept that goes far beyond acceptance. They called it amor fati — the love of fate.\n\nNot just tolerating what happens. Not just enduring it. Loving it. Every setback, every loss, every unwanted change. Because in the Stoic view, the cosmos is rational. Everything is connected. Fighting causality is fighting reality itself.\n\nAnd fighting reality is the definition of suffering.",
      source: 'Marcus Aurelius',
      style: 'principle',
      followUp: "Marcus Aurelius practiced this during a plague that killed five million people. If he could love his fate then, you can begin to love yours now.",
      nextStepId: 'plague-tapflow',
    },
    {
      id: 'plague-tapflow',
      type: 'tapFlow',
      title: 'Marcus in the Plague',
      instructions: [
        'Rome. 165 AD. A plague sweeps the empire. Death is everywhere.',
        'Marcus Aurelius — emperor, philosopher, father — watches his people die.',
        'He cannot stop it. No edict, no army, no prayer will change what is happening.',
        'And yet, in his private journal, he writes: "Accept the things to which fate binds you."',
        'Not because the plague is good. Because fighting it with anguish helps no one.',
        'He channels his energy into what he CAN do — organize relief, comfort the grieving, lead with clarity.',
      ],
      closingText: "He loved his fate. Not the plague. His fate — which included the plague, and also included his ability to respond.",
      style: 'grounding',
      nextStepId: 'deeper-insight',
    },
    {
      id: 'deeper-insight',
      type: 'insight',
      text: "This is not 'everything happens for a reason' said with a smile and a shrug. That's cheap comfort.\n\nThis is something harder and more honest: everything is caused. Everything is connected. And fighting causality — raging against what already happened — IS the suffering. The event is the event. Your resistance to the event is what turns pain into torment.",
      style: 'revelation',
      nextStepId: 'river-choice',
    },
    {
      id: 'river-choice',
      type: 'choice',
      question: 'Where are you with this idea?',
      options: [
        {
          id: 'accept',
          label: 'I can accept. Loving feels like too much.',
          subtext: "Acceptance I understand. Love feels impossible.",
          nextStepId: 'accept-insight',
          storeAs: 'fatiResponse',
        },
        {
          id: 'resistance-is-suffering',
          label: 'Resisting IS the suffering. I feel that.',
          subtext: "The war against reality is what's breaking me.",
          nextStepId: 'resistance-insight',
          storeAs: 'fatiResponse',
        },
      ],
    },
    {
      id: 'accept-insight',
      type: 'insight',
      text: "Good. Acceptance is where it begins. Amor fati is where it leads.\n\nYou don't have to love your fate today. Start by simply stopping the war. Put down the weapons you're using against what already happened. Let reality be what it is without adding your resistance on top of it.\n\nAcceptance is the doorway. Amor fati is the room on the other side. You'll walk through when you're ready.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'resistance-insight',
      type: 'insight',
      text: "You see it. The equation the Stoics discovered two thousand years ago:\n\nSuffering = Reality + Resistance.\n\nRemove the resistance, and what's left? Reality. Which may be painful — but pain without resistance is just sensation. It moves through you. It doesn't become your identity. It doesn't eat your life.\n\nYou've been doubling your pain by fighting it. Today, you stop.",
      style: 'revelation',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: 'Name something painful you can now see was necessary for who you\'ve become. Something you fought — that shaped you.',
      minimumWords: 5,
      depthPrompts: [
        "Go deeper. How did this painful thing build something in you?",
        "What would be missing from you without it?",
      ],
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Marcus wrote in the depths of plague and war: 'Accept the things to which fate binds you, and love the people with whom fate brings you together.' He didn't say it was easy. He said it was necessary. You've taken the first step toward ending your war with reality.",
        ],
        byChoice: {
          accept: [
            "You chose acceptance. That's not a small thing — most people never get there. They spend their entire lives fighting what already happened. You've put down the weapons. When you're ready, amor fati will transform acceptance into something extraordinary: gratitude for everything, even the hard parts.",
          ],
          'resistance-is-suffering': [
            "You saw the equation: suffering equals reality plus resistance. That insight is ancient, but you made it personal today. The next time you feel that familiar tightness — the rage against what is — remember: the tightness IS the resistance. Let it go, and what remains is just life, happening.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      statement: 'I love my fate. Not because it is easy, but because it is mine.',
      confirmLabel: 'I love my fate',
      style: 'release',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 13: THE UNREACHABLE STAR
// ─────────────────────────────────────────────────────────────────────────────

const lesson13: FlexibleLesson = {
  id: 'stoic-13-unreachable-star',
  slug: 'unreachable-star',
  order: 3,
  title: 'The Unreachable Star',
  subtitle: "Perfection you'll never reach — and why that's the point",
  description: 'Discover why the Stoics set a goal they knew was impossible — and why it changed everything.',
  coreConceptTag: 'sage-ideal',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '⭐', color: '#7c3aed' },
  teaserText: "Tomorrow you'll discover why the Stoics set a goal they knew was impossible — and why it changed everything.",
  exercises: stoicLesson13Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You've grown. You can feel it. The Stoic practices are working — you catch your reactions faster, you see things more clearly, you respond instead of react.\n\nBut you still snap at the people you love. You still make choices you regret. You still fall short of who you want to be.\n\nHere's the Stoic secret no one tells you: you will ALWAYS fall short. And that's the entire point.",
      subtext: "The star is unreachable. Reach for it anyway.",
      continueLabel: "Tell me more",
      mood: 'curiosity',
      nextStepId: 'shortfall-check',
    },
    {
      id: 'shortfall-check',
      type: 'resonanceCheck',
      prompt: 'Where do you still fall short?',
      instruction: 'Tap what\'s honest',
      options: [
        { id: 'patience', text: 'Patience' },
        { id: 'discipline', text: 'Self-discipline' },
        { id: 'courage', text: 'Courage' },
        { id: 'kindness', text: 'Kindness' },
        { id: 'honesty', text: 'Honesty' },
        { id: 'consistency', text: 'Consistency' },
        { id: 'humility', text: 'Humility' },
        { id: 'presence', text: 'Presence' },
      ],
      minSelections: 1,
      maxSelections: 4,
      storeAs: 'shortfalls',
      nextStepId: 'frustration-scale',
    },
    {
      id: 'frustration-scale',
      type: 'scaleRating',
      prompt: 'How frustrated are you by your imperfections?',
      lowLabel: 'Barely',
      highLabel: 'Deeply',
      steps: 5,
      storeAs: 'imperfection-frustration',
      responsesByRange: {
        low: "You've made peace with being imperfect. The Stoics would respect that. Today we give that peace a name.",
        mid: "Some days it bothers you, some days it doesn't. Today you'll learn why the frustration itself is the wrong target.",
        high: "That frustration is eating you. And here's the paradox — the Stoics would say the frustration is the bigger problem than the imperfection. Today we dissolve it.",
      },
      nextStepId: 'sage-insight',
    },
    {
      id: 'sage-insight',
      type: 'insight',
      text: "The Stoics imagined the Sage — the perfectly wise human being. Someone who always acts with perfect virtue, perfect judgment, perfect calm.\n\nHere's the thing: they knew no one would ever get there. Not Zeno, who founded the school. Not Epictetus, who survived slavery. Not Marcus, who ruled an empire.\n\nThe Sage isn't a destination. It's a North Star. You navigate by it. You never arrive.",
      source: 'Zeno of Citium',
      style: 'principle',
      followUp: "When Zeno himself was asked if he was a Sage, he said no. The founder of Stoicism couldn't meet his own standard. That wasn't failure. That was the design.",
      nextStepId: 'zeno-tapflow',
    },
    {
      id: 'zeno-tapflow',
      type: 'tapFlow',
      title: 'The Founder\'s Confession',
      instructions: [
        'Zeno of Citium. The man who started it all.',
        'Students asked him: "Are you a Sage, teacher?"',
        'He said no. Simply, honestly, without shame.',
        'Seneca, centuries later: "I am not a Sage, and I never shall be."',
        'The greatest Stoics who ever lived — all of them falling short. All of them reaching anyway.',
      ],
      closingText: "If the founders couldn't reach the star, why did they keep reaching?",
      style: 'grounding',
      nextStepId: 'prokope-insight',
    },
    {
      id: 'prokope-insight',
      type: 'insight',
      text: "Because the Stoics had another word: prokope. Progress.\n\nThe goal was never perfection. The goal was always improvement. Every day slightly less foolish than the day before. Every reaction a little more measured. Every choice a little more aligned with who you want to be.\n\nProkope. Not the Sage, but the prokoptōn — the one making progress. That's you. That's all any of us can be. And that's enough.",
      style: 'revelation',
      nextStepId: 'star-choice',
    },
    {
      id: 'star-choice',
      type: 'choice',
      question: 'How do you feel about an unreachable goal?',
      options: [
        {
          id: 'need-finish-line',
          label: 'I need a finish line',
          subtext: "Unreachable goals feel pointless to me",
          nextStepId: 'finish-line-insight',
          storeAs: 'sageResponse',
        },
        {
          id: 'journey-enough',
          label: 'The journey is enough',
          subtext: "I don't need to arrive to keep walking",
          nextStepId: 'journey-insight',
          storeAs: 'sageResponse',
        },
      ],
    },
    {
      id: 'finish-line-insight',
      type: 'insight',
      text: "That's fair. And the Stoics would agree — partially. Set intermediate goals. Master patience this month. Build courage this year. Cross those finish lines and celebrate them.\n\nBut know this: behind every finish line is another horizon. You'll complete one goal and discover ten more. That's not a flaw in the system. That's the nature of growth. The finish lines are real. The final finish line isn't. And that's what keeps you moving.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'journey-insight',
      type: 'insight',
      text: "You're a natural prokoptōn. The Stoics would recognize you immediately — someone who finds meaning in the walking, not just the arriving.\n\nThis is rare. Most people quit when they realize the destination is unreachable. You understand that the reaching IS the living. Every day you practice virtue is a day well lived, regardless of whether you achieve perfection. The star doesn't need to be reached. It needs to be followed.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: 'Describe the Sage version of yourself. What does that person look like? And what one quality can you practice today to move closer?',
      minimumWords: 5,
      depthPrompts: [
        "Get specific. How does your Sage self handle the situations that trip you up?",
      ],
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Zeno founded an entire school of philosophy around a standard he knew he'd never meet. That's not hypocrisy. That's wisdom. The Sage is a mirror you hold up to yourself — not to feel ashamed, but to see where to grow next. You're a prokoptōn. You're making progress. That's all the Stoics ever asked.",
        ],
        byChoice: {
          'need-finish-line': [
            "You want something to cross. Good — set those intermediate goals and crush them. But when you cross one and see another beyond it, don't despair. That's not failure. That's the infinite game of becoming. Every finish line you cross makes you more capable of reaching the next one.",
          ],
          'journey-enough': [
            "You understand something most people never grasp: the walk is the destination. The Stoics practiced virtue not to arrive at wisdom but because practicing virtue IS wisdom. You're already living the lesson. Keep walking. The star will keep shining.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      statement: 'I will never be perfect. I will always be better than yesterday. The star is unreachable. I reach for it anyway.',
      confirmLabel: 'I reach anyway',
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 14: CITIZENS OF EVERYWHERE
// ─────────────────────────────────────────────────────────────────────────────

const lesson14: FlexibleLesson = {
  id: 'stoic-14-citizens-everywhere',
  slug: 'citizens-everywhere',
  order: 4,
  title: 'Citizens of Everywhere',
  subtitle: 'Your tribe is the entire human race',
  description: 'Learn why a Roman emperor believed he owed something to every person on Earth.',
  coreConceptTag: 'cosmopolitanism',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '🌐', color: '#6d28d9' },
  teaserText: "Tomorrow you'll learn why a Roman emperor believed he owed something to every person on Earth.",
  exercises: stoicLesson14Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You're scrolling. A headline about suffering somewhere far away. A photo of someone whose name you'll never know. A flicker of feeling — a tightness in your chest, a flash of sadness.\n\nThen you keep scrolling.",
      subtext: "That flicker matters more than you think.",
      continueLabel: "I know that flicker",
      mood: 'tension',
      nextStepId: 'flicker-scenario',
    },
    {
      id: 'flicker-scenario',
      type: 'scenario',
      narrative: "That flicker is your humanity. Most people suppress it. Too much suffering, can't carry it all, not my problem.\n\nBut the Stoics said something radical: that person IS your problem. Not because you caused their suffering. Because they are your fellow citizen. The Stoics said: don't suppress the flicker. Expand it.",
      continueLabel: "Expand it how?",
      mood: 'curiosity',
      nextStepId: 'circles-check',
    },
    {
      id: 'circles-check',
      type: 'resonanceCheck',
      prompt: 'Where do your circles of concern end?',
      instruction: 'Tap the furthest circle you genuinely feel responsible for',
      options: [
        { id: 'family', text: 'Immediate family' },
        { id: 'friends', text: 'Close friends' },
        { id: 'community', text: 'My community' },
        { id: 'country', text: 'My country' },
        { id: 'beliefs', text: 'People who share my beliefs' },
        { id: 'all-humans', text: 'All humans' },
        { id: 'all-living', text: 'All living things' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'circle-boundaries',
      nextStepId: 'oikeiosis-insight',
    },
    {
      id: 'oikeiosis-insight',
      type: 'insight',
      text: "The Stoic philosopher Hierocles imagined human concern as concentric circles. At the center: yourself. Then family. Then friends. Community. Country. All of humanity.\n\nHis challenge to philosophers: draw the outer circles inward. Treat your community like family. Treat strangers like community. Treat all humans like neighbors.\n\nThis wasn't sentimental. It was a practice — the deliberate expansion of who you consider 'us.'",
      source: 'Hierocles',
      style: 'principle',
      followUp: "The Stoics called this oikeiosis — the process of making what is foreign feel familiar, what is distant feel close.",
      nextStepId: 'circles-tapflow',
    },
    {
      id: 'circles-tapflow',
      type: 'tapFlow',
      title: 'Expanding the Circles',
      instructions: [
        'Start with yourself. You, here, now. The center of your world.',
        'First circle: the people you love most. Feel the warmth of that connection.',
        'Wider: your friends, your community. People who share your daily life.',
        'Wider still: your city. People you pass on the street. Each one carrying a universe inside them.',
        'Your country. Millions of stories you\'ll never hear. All of them real.',
        'Now: all humans. Every person on Earth. Different languages, different lives, same capacity for suffering and joy.',
        'The Stoics said: this is your real city. The cosmos. Every human is your neighbor.',
      ],
      closingText: "Hierocles asked: can you treat the outer circle with the care you give the inner?",
      style: 'cosmic',
      nextStepId: 'width-scale',
    },
    {
      id: 'width-scale',
      type: 'scaleRating',
      prompt: 'How wide are your genuine circles of concern?',
      lowLabel: 'Very narrow',
      highLabel: 'Very wide',
      steps: 5,
      storeAs: 'circle-width',
      responsesByRange: {
        low: "Narrow circles aren't a moral failure. They're where most people start. The practice is expansion — and you're practicing right now.",
        mid: "You care beyond yourself, but the edges get fuzzy. That's human. The Stoics didn't expect perfection. They expected effort.",
        high: "Your circles are already wide. You feel the pull of distant suffering. That's not a burden — it's the mark of a philosophical life.",
      },
      nextStepId: 'cosmo-insight',
    },
    {
      id: 'cosmo-insight',
      type: 'insight',
      text: "Marcus Aurelius wrote: 'My city and fatherland, as Antoninus, is Rome; as a human being, it is the world.'\n\nThis is cosmopolitanism — not as a modern buzzword, but as a Stoic ethical principle. Every human shares rational nature. Every human is capable of virtue. Every human, therefore, is your fellow citizen.\n\nThis isn't a metaphor. It's a literal ethical obligation. You owe something to every person you will never meet.",
      source: 'Marcus Aurelius',
      sourceBook: 'Meditations',
      style: 'principle',
      nextStepId: 'cosmo-choice',
    },
    {
      id: 'cosmo-choice',
      type: 'choice',
      question: 'What\'s your honest reaction?',
      options: [
        {
          id: 'overwhelming',
          label: "It's overwhelming — I can't carry the world's weight",
          subtext: "The scope of suffering is paralyzing",
          nextStepId: 'overwhelming-insight',
          storeAs: 'cosmoResponse',
        },
        {
          id: 'disconnected',
          label: "I don't feel connected to strangers",
          subtext: "Caring about everyone feels abstract",
          nextStepId: 'disconnected-insight',
          storeAs: 'cosmoResponse',
        },
      ],
    },
    {
      id: 'overwhelming-insight',
      type: 'insight',
      text: "Cosmopolitanism isn't about suffering more. It's about caring wider.\n\nYou don't need to carry the world's pain on your shoulders. That would crush anyone. But you can let your concern extend past your front door. A kind word to a stranger. Attention to suffering you'd normally scroll past. A small act of generosity with vast ripple effects.\n\nYou can't save everyone. But you can refuse to pretend they don't exist.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'disconnected-insight',
      type: 'insight',
      text: "Connection to strangers isn't a feeling. It's a fact.\n\nYou breathe the same air. You share the same rational nature. You experience the same range of joy and suffering. You are, biologically and philosophically, the same kind of being.\n\nThe feeling of connection may come later. But the connection itself is already there. The Stoics didn't ask you to feel warmth for every human. They asked you to recognize the truth: you are made of the same stuff, bound by the same nature.",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: 'Name one person or group outside your usual circle of concern. How could you draw them closer — even slightly?',
      minimumWords: 5,
      encouragements: [
        "Think small. One person. One group. One act.",
        "Drawing closer doesn't mean grand gestures. It means paying attention.",
      ],
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Marcus Aurelius commanded armies, yet he wrote: 'We were born to work together, like feet, like hands, like eyelids, like the rows of upper and lower teeth.' He saw every human as part of the same body. When one part suffers, the whole body feels it. You just expanded your circles. That expansion is the beginning of a philosophical life.",
        ],
        byChoice: {
          overwhelming: [
            "You're not meant to save the world alone. The Stoics didn't ask for heroic self-sacrifice. They asked for expanded awareness. Notice the stranger. Acknowledge the suffering you'd normally scroll past. Small acts, wide circles. That's cosmopolitanism in practice.",
          ],
          disconnected: [
            "Connection to strangers is a practice, not a personality trait. Start with recognition: that person on the street has the same fears you do. The same hopes. The same capacity for suffering. You don't have to feel a surge of love. You just have to see them as real. The feeling follows the seeing.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      statement: 'My city is the cosmos. My neighbor is humanity. My obligation extends as far as reason reaches.',
      confirmLabel: 'I am a citizen of everywhere',
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 15: THE PHILOSOPHER'S LIFE (FINALE)
// ─────────────────────────────────────────────────────────────────────────────

const lesson15: FlexibleLesson = {
  id: 'stoic-15-philosophers-life',
  slug: 'philosophers-life',
  order: 5,
  title: "The Philosopher's Life",
  subtitle: "Everything you've learned. One life to live.",
  description: 'The final lesson. Everything comes together into one philosophy for living.',
  coreConceptTag: 'eudaimonia',
  xpReward: 25,
  estimatedMinutes: 7,
  thumbnail: { icon: '🏛️', color: '#4338ca' },
  teaserText: "The final lesson. Everything comes together.",
  exercises: stoicLesson15Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Fourteen days ago, you walked through a door. You didn't know what was behind it — just a word. Stoicism.\n\nYou've built something since then. Not a habit. Not a routine. A philosophy. A way of seeing the world and your place in it.\n\nToday, you look back at the cathedral you've been building — and see it whole for the first time.",
      subtext: "The final lesson is also the first day of the rest of your philosophical life.",
      continueLabel: "Show me the cathedral",
      mood: 'hope',
      nextStepId: 'cathedral-tapflow',
    },
    {
      id: 'cathedral-tapflow',
      type: 'tapFlow',
      title: 'The Cathedral',
      instructions: [
        'Lesson 1: You discovered the Dichotomy of Control. What you can change and what you can\'t. The foundation of everything.',
        'Lesson 2: You met your Inner Citadel. The fortress inside you that nothing external can breach.',
        'Lesson 3: You learned to Observe Before Reacting. The pause between stimulus and response where your freedom lives.',
        'Lesson 4: You discovered Negative Visualization. Imagining loss to deepen gratitude for what remains.',
        'Lesson 5: You faced Voluntary Discomfort. Choosing hardship before it chooses you.',
        'Lesson 6: You found your Roles and Duties. The obligations that give life structure and meaning.',
        'Lesson 7: You practiced Turning Obstacles. Making every setback into fuel.',
        'Lesson 8: You examined your Desires. The difference between what you want and what you need.',
        'Lesson 9: You confronted Memento Mori. Death as the great clarifier.',
        'Lesson 10: You learned The Evening Review. Examining each day with honest eyes.',
        'Lesson 11: You practiced the View from Above. Cosmic perspective that shrinks problems and expands awareness.',
        'Lesson 12: You met Amor Fati. Loving your fate — all of it, even the painful parts.',
        'Lesson 13: You saw the Unreachable Star. The Sage ideal you\'ll never reach but always chase.',
        'Lesson 14: You became a Citizen of Everywhere. Your tribe is the entire human race.',
      ],
      closingText: "Fourteen pillars. One cathedral. Your philosophy.",
      style: 'cosmic',
      nextStepId: 'resonance-review',
    },
    {
      id: 'resonance-review',
      type: 'resonanceCheck',
      prompt: 'Which teachings changed you most?',
      instruction: 'Pick the lessons that hit deepest — up to 4',
      options: [
        { id: 'control', text: 'Dichotomy of Control' },
        { id: 'citadel', text: 'Inner Citadel' },
        { id: 'observe', text: 'Observe Before Reacting' },
        { id: 'negative-vis', text: 'Negative Visualization' },
        { id: 'discomfort', text: 'Voluntary Discomfort' },
        { id: 'roles', text: 'Roles and Duties' },
        { id: 'obstacles', text: 'Turning Obstacles' },
        { id: 'desires', text: 'Examining Desires' },
        { id: 'memento-mori', text: 'Memento Mori' },
        { id: 'evening-review', text: 'Evening Review' },
        { id: 'view-above', text: 'View from Above' },
        { id: 'amor-fati', text: 'Amor Fati' },
        { id: 'sage-ideal', text: 'Unreachable Star' },
        { id: 'cosmopolitanism', text: 'Citizens of Everywhere' },
      ],
      minSelections: 1,
      maxSelections: 4,
      storeAs: 'deepest-teachings',
      nextStepId: 'eudaimonia-insight',
    },
    {
      id: 'eudaimonia-insight',
      type: 'insight',
      text: "Every teaching you've practiced points to one thing: eudaimonia.\n\nNot happiness in the modern sense — not pleasure, not comfort, not success. Eudaimonia is the good life. The flourishing life. A life lived in accordance with virtue.\n\nThe Stoics believed that a virtuous life IS a good life. Not 'will lead to' a good life. IS one. Virtue isn't a means to an end. It's the end itself.",
      source: 'Zeno of Citium',
      style: 'principle',
      nextStepId: 'nature-insight',
    },
    {
      id: 'nature-insight',
      type: 'insight',
      text: "'Living according to nature' — the central Stoic formula. But nature here doesn't mean trees and rivers. It means YOUR nature. Human nature. Rational nature.\n\nTo live according to nature is to use your reason fully in every decision. To align your choices with wisdom, courage, justice, and temperance. Not perfectly. Not like a Sage. But deliberately, every single day.",
      style: 'revelation',
      followUp: "This is what you've been building toward. Not a set of tricks. A way of being.",
      nextStepId: 'closeness-scale',
    },
    {
      id: 'closeness-scale',
      type: 'scaleRating',
      prompt: 'How close are you to living a philosophical life?',
      lowLabel: 'Far away',
      highLabel: 'Beginning',
      steps: 5,
      storeAs: 'philosophical-closeness',
      responsesByRange: {
        low: "Far away is honest. But far away and walking is better than close and standing still. You're walking.",
        mid: "You're in the middle — and the middle is exactly where a prokoptōn belongs. Progress, not perfection.",
        high: "You feel the beginning. That's because it IS the beginning. Not the beginning of learning. The beginning of living it.",
      },
      nextStepId: 'foundation-choice',
    },
    {
      id: 'foundation-choice',
      type: 'choice',
      question: 'What foundation feels strongest for your philosophical life?',
      options: [
        {
          id: 'inner-strength',
          label: 'Inner strength — mastering myself',
          subtext: "The citadel within is my foundation",
          nextStepId: 'epictetus-insight',
          storeAs: 'foundationType',
        },
        {
          id: 'outward-purpose',
          label: 'Outward purpose — serving something larger',
          subtext: "Duty and contribution are my foundation",
          nextStepId: 'marcus-insight',
          storeAs: 'foundationType',
        },
      ],
    },
    {
      id: 'epictetus-insight',
      type: 'insight',
      text: "Epictetus would recognize you. Born a slave, he built his entire philosophy on one truth: you cannot control what happens to you, but you can always control how you respond.\n\nYour foundation is the Inner Citadel. No one can breach it without your permission. Every Stoic practice you've learned — the pause, the reframe, the review — they all strengthen these walls. Your power lives inside you. Everything external is borrowed.",
      source: 'Epictetus',
      style: 'principle',
      nextStepId: 'practice-choice',
    },
    {
      id: 'marcus-insight',
      type: 'insight',
      text: "Marcus Aurelius would recognize you. An emperor who saw power not as privilege but as obligation. Every morning he reminded himself: you exist to serve.\n\nYour foundation is purpose beyond yourself. The roles you fill, the people you serve, the cosmic citizenship you carry. Stoicism isn't a retreat from the world. It's a way of engaging with it more fully, more wisely, more generously.",
      source: 'Marcus Aurelius',
      style: 'principle',
      nextStepId: 'practice-choice',
    },
    {
      id: 'practice-choice',
      type: 'choice',
      question: 'How will you practice Stoicism going forward?',
      options: [
        {
          id: 'morning-practice',
          label: 'Morning practice — start each day like a Stoic',
          subtext: "Begin every morning with intention",
          nextStepId: 'morning-tapflow',
          storeAs: 'practiceType',
        },
        {
          id: 'response-protocol',
          label: 'Response protocol — meet each challenge like a Stoic',
          subtext: "Handle every difficulty with philosophy",
          nextStepId: 'response-tapflow',
          storeAs: 'practiceType',
        },
      ],
    },
    {
      id: 'morning-tapflow',
      type: 'tapFlow',
      title: 'The Morning Protocol',
      instructions: [
        'Seneca began every morning the same way. So can you.',
        'First: remember death. Not morbidly. Clearly. This day could be your last. Live accordingly.',
        'Second: rehearse the day. What challenges will come? How will you meet them with virtue?',
        'Third: check your desires. What do you want today? Is it within your control? If not, release it.',
        'Fourth: commit to your roles. Father, mother, friend, worker, citizen. What does each role demand today?',
        'Five minutes. Every morning. A philosophical life begins before breakfast.',
      ],
      closingText: "Seneca wrote: 'Begin at once to live, and count each separate day as a separate life.'",
      style: 'grounding',
      nextStepId: 'converge-insight',
    },
    {
      id: 'response-tapflow',
      type: 'tapFlow',
      title: 'The Response Protocol',
      instructions: [
        'Zeno taught his students to meet every challenge the same way. Here is the protocol.',
        'First: catch the impression. Something happened. Notice it before you react to it.',
        'Second: examine it. Is this within my control? Is my initial reaction based on reality or assumption?',
        'Third: classify the emotion. Is this anger? Fear? Desire? Name it. Naming it weakens its grip.',
        'Fourth: respond from the citadel. Not from impulse. From your trained, philosophical center.',
        'Fifth: act with virtue. Choose the response that wisdom, courage, justice, or temperance demands.',
      ],
      closingText: "Every challenge is a chance to practice. Every reaction is a choice.",
      style: 'fearless',
      nextStepId: 'converge-insight',
    },
    {
      id: 'converge-insight',
      type: 'insight',
      text: "Here's what unites every Stoic who ever lived — Epictetus the slave, Marcus the emperor, Seneca the senator, Zeno the merchant.\n\nNone of them were Sages. All of them were prokoptōn — progressors. Students until the day they died. Imperfect people practicing virtue imperfectly.\n\nJust like you.\n\nThe difference between a philosopher and everyone else isn't wisdom. It's the commitment to keep practicing.",
      style: 'revelation',
      nextStepId: 'final-reflection',
    },
    {
      id: 'final-reflection',
      type: 'reflection',
      prompt: 'Write your personal Stoic creed. In 2-3 sentences, who are you now? What do you stand for? How will you live?',
      minimumWords: 10,
      encouragements: [
        "Make it yours. Not Epictetus's words. Not Marcus's. Yours.",
        "What would you want to read back to yourself on the hardest day of your life?",
      ],
      depthPrompts: [
        "Go deeper. This is the sentence you'll carry forward. Make it true.",
      ],
      nextStepId: 'final-mentor',
    },
    {
      id: 'final-mentor',
      type: 'mentor',
      responses: {
        default: [
          "Epictetus, from his small room: 'The Inner Citadel is yours. Nothing external can breach it. You have always been free.'",
          "Marcus, from his journal: 'You have duties to fulfill. Not because you are emperor. Because you are human. Serve well.'",
          "Seneca, from his study: 'Time is the one thing you cannot recover. Spend it as if you know its value. Because now, you do.'",
          "Zeno, from the painted porch: 'You are not wise. You are becoming wiser. That is the only journey that matters. Keep walking.'",
        ],
        byChoice: {
          'inner-strength': [
            "Your citadel is built. Not from stone — from practice. From every moment you paused instead of reacted, from every evening you reviewed your day with honest eyes. Epictetus would tell you: the fortress was always there. You just learned to live in it.",
          ],
          'outward-purpose': [
            "Marcus would say: your life is not your own. It belongs to your roles, your duties, your fellow citizens. That's not a burden. That's meaning. You've found something worth serving. Now go serve it with everything you have.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      preText: "You are not a Sage. You are something better.",
      statement: 'I am a prokoptōn. I am not wise. I am becoming wiser. My philosophy lives in my actions, not my words.',
      confirmLabel: 'I am becoming',
      style: 'strength',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
      customMessage: 'You have completed the Stoic path. Not as a Sage. As something better: a student who will never stop.',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// ASSEMBLE CHAPTER 3: CITIZEN OF THE COSMOS
// ─────────────────────────────────────────────────────────────────────────────

export const stoicChapter3_CitizenOfCosmos: FlexibleChapter = {
  id: 'chapter-stoic-citizen-of-cosmos',
  slug: 'citizen-of-cosmos',
  name: 'Citizen of the Cosmos',
  subtitle: 'You are part of something immeasurably vast',
  description: 'Five lessons that expand your perspective from self to cosmos. See from above, accept fate with grace, strive toward an ideal, claim your citizenship in humanity, and weave all Stoic teachings into one life.',
  order: 3,
  iconName: 'Globe',
  lessons: [lesson11, lesson12, lesson13, lesson14, lesson15],
};

export default stoicChapter3_CitizenOfCosmos;
