// ═══════════════════════════════════════════════════════════════════════════
// CHAPTER 2: THE PHILOSOPHER'S FIRE - Philosophy that bleeds, breathes, and acts
// ═══════════════════════════════════════════════════════════════════════════

import type { FlexibleLesson, FlexibleChapter, LessonStep } from '@/types/lessons';
import { stoicLesson6Exercises, stoicLesson7Exercises, stoicLesson8Exercises, stoicLesson9Exercises, stoicLesson10Exercises } from './stoicismExerciseContent';

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 6: FATE PERMITTING (Reserve Clause)
// ─────────────────────────────────────────────────────────────────────────────

const lesson6: FlexibleLesson = {
  id: 'stoic-6-fate-permitting',
  slug: 'fate-permitting',
  order: 1,
  title: 'Fate Permitting',
  subtitle: 'Plan everything. Grip nothing.',
  description: 'Learn the ancient art of total effort with total detachment from outcomes.',
  coreConceptTag: 'reserve-clause',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '🎯', color: '#8b5cf6' },
  teaserText: "Tomorrow you'll learn the ancient trick of giving everything you have while staying at peace with any result.",
  exercises: stoicLesson6Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "You've been working toward something for months. Pouring yourself into it. Late nights, sacrifice, everything you had. And now the decision is out of your hands. Someone else decides. The universe decides. The wait is killing you.",
      subtext: "You did everything right. But the outcome isn't yours to control.",
      continueLabel: "I know this feeling",
      mood: 'tension',
      nextStepId: 'grip-check',
    },
    {
      id: 'grip-check',
      type: 'resonanceCheck',
      prompt: "What outcome are you gripping tightest right now?",
      instruction: "Tap what resonates most",
      options: [
        { id: 'career', text: 'Career — a job, promotion, or opportunity' },
        { id: 'relationship', text: 'Relationship — someone I want to be with or keep' },
        { id: 'health', text: 'Health — a diagnosis, recovery, or body goal' },
        { id: 'financial', text: 'Financial — money, security, stability' },
        { id: 'creative', text: 'Creative — a project, dream, or calling' },
        { id: 'academic', text: 'Academic — a grade, admission, or qualification' },
      ],
      minSelections: 1,
      maxSelections: 2,
      storeAs: 'outcome-grip',
      nextStepId: 'peace-scale',
    },
    {
      id: 'peace-scale',
      type: 'scaleRating',
      prompt: "How much of your inner peace is tied to this outcome?",
      lowLabel: 'Barely any',
      highLabel: 'Completely',
      steps: 5,
      storeAs: 'peace-tied',
      responsesByRange: {
        low: "You already have some distance. Let's sharpen it into a philosophy.",
        mid: "Part of you knows the outcome doesn't define you. Part of you can't let go. Let's work with that.",
        high: "Your peace is hostage to something you can't control. That's exactly what we're about to fix.",
      },
      nextStepId: 'reserve-insight',
    },
    {
      id: 'reserve-insight',
      type: 'insight',
      text: "The Stoics had a practice called the Reserve Clause — in Latin, 'fate permitting.' It's deceptively simple: pursue your goals with everything you have, but mentally append 'fate permitting' to every plan.\n\nNot as resignation. As liberation.",
      style: 'principle',
      followUp: "It means: I will do my absolute best. And I will be at peace with whatever comes.",
      nextStepId: 'marcus-tapflow',
    },
    {
      id: 'marcus-tapflow',
      type: 'tapFlow',
      title: "Marcus Aurelius at War",
      instructions: [
        'Rome is at war. Marcus Aurelius plans his campaign with precision.',
        'Every detail considered. Every supply line mapped. Every contingency prepared.',
        'He gives his full genius to the strategy.',
        'But in his journal that night, he writes something strange.',
        '"I will do what must be done... fate permitting."',
        'Not laziness. Not doubt. Total preparation combined with total acceptance.',
        'He planned as if everything depended on him.',
        'And accepted as if nothing did.',
        'This is the secret: give everything. Grip nothing.',
      ],
      closingText: "The effort is yours. The outcome belongs to the universe.",
      style: 'cosmic',
      nextStepId: 'formula-insight',
    },
    {
      id: 'formula-insight',
      type: 'insight',
      text: "THE RESERVE CLAUSE FORMULA:\n\n1. Choose your goal with clarity.\n2. Pursue it with total effort — nothing held back.\n3. Append 'fate permitting' to every plan.\n4. Accept either outcome with equal dignity.\n\nThis isn't giving up. It's giving everything while refusing to let the result own you.",
      style: 'principle',
      nextStepId: 'separation-choice',
    },
    {
      id: 'separation-choice',
      type: 'choice',
      instruction: "Be honest with yourself",
      question: "Where are you with this idea?",
      options: [
        {
          id: 'can-separate',
          label: 'I can separate effort from outcome',
          subtext: 'I see the difference between trying and needing',
          nextStepId: 'already-insight',
          storeAs: 'reserveClauseStance',
        },
        {
          id: 'identity-wrapped',
          label: 'My identity is wrapped up in this outcome',
          subtext: "If I don't get this, I don't know who I am",
          nextStepId: 'identity-insight',
          storeAs: 'reserveClauseStance',
        },
      ],
    },
    {
      id: 'already-insight',
      type: 'insight',
      text: "You already understand something most people never learn: you are not your results. Your effort is the only thing truly yours. Outcomes are collaborations between your effort and a thousand forces beyond your control.\n\nKeep giving everything. Keep gripping nothing. You're already practicing what Marcus spent a lifetime learning.",
      style: 'revelation',
      nextStepId: 'reflection',
    },
    {
      id: 'identity-insight',
      type: 'insight',
      text: "When your identity depends on an outcome, you've handed the keys to your inner citadel to fate. You've told the universe: 'You decide who I am.'\n\nBut you are not the promotion. You are not the relationship. You are not the acceptance letter. You are the person who showed up fully, regardless of what happened next. That can never be taken from you.",
      style: 'revelation',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "Write down what you want most right now. Then add 'fate permitting.' What shifts inside you when you read it back?",
      minimumWords: 5,
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Marcus Aurelius ran an empire with this philosophy. He planned wars, governed millions, and faced plagues — all with 'fate permitting' written into every intention. Not because he didn't care. Because he cared enough to give everything without letting the result destroy him.",
        ],
        byChoice: {
          'can-separate': [
            "You can already feel the difference between effort and outcome. That's rare. Most people confuse the two their entire lives. Hold onto this clarity — it will serve you when the stakes are highest and the outcome is least in your control.",
          ],
          'identity-wrapped': [
            "You were honest about something most people won't admit: that your worth feels tied to what happens next. Marcus felt this too. He wanted to be a philosopher, not an emperor. But he learned that who you are is defined by how you show up, not by what you receive. Start there.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      preText: "This is the Stoic way.",
      statement: "I will give everything. I will grip nothing. My worth is in the effort, not the outcome.",
      confirmLabel: "Fate permitting",
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 7: THE LAST MORNING (Memento Mori)
// ─────────────────────────────────────────────────────────────────────────────

const lesson7: FlexibleLesson = {
  id: 'stoic-7-the-last-morning',
  slug: 'the-last-morning',
  order: 2,
  title: 'The Last Morning',
  subtitle: 'Today could be the day. Live accordingly.',
  description: 'Discover how meditating on death can make every single day feel more alive.',
  coreConceptTag: 'memento-mori',
  xpReward: 23,
  estimatedMinutes: 6,
  thumbnail: { icon: '⏳', color: '#7c3aed' },
  teaserText: "Tomorrow you'll discover how thinking about death can make every single day feel more alive.",
  exercises: stoicLesson7Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Tomorrow morning. Light comes through your window. You feel the warmth on your face. You hear the sounds of a world waking up. Everything is ordinary. Everything is perfect.",
      subtext: "What if this were the last time?",
      continueLabel: "Go on",
      mood: 'tension',
      nextStepId: 'scenario-2',
    },
    {
      id: 'scenario-2',
      type: 'scenario',
      narrative: "This isn't hypothetical. Not really. You don't know how many mornings you have left. Nobody does. The person reading this yesterday might not be reading it tomorrow. That's not morbid. That's the most important fact of your life.",
      bridgeQuestion: "So what will you do with the mornings you have?",
      continueLabel: "I'm listening",
      mood: 'tension',
      nextStepId: 'unfinished-check',
    },
    {
      id: 'unfinished-check',
      type: 'resonanceCheck',
      prompt: "What would hurt most to leave unfinished?",
      instruction: "Tap what hits hardest",
      options: [
        { id: 'conversation', text: 'A conversation I keep putting off' },
        { id: 'project', text: 'A project that matters deeply to me' },
        { id: 'forgiveness', text: 'A person I need to forgive' },
        { id: 'unsaid', text: 'Words I haven\'t said to someone I love' },
        { id: 'risk', text: 'A risk I\'ve been too afraid to take' },
        { id: 'unlived', text: 'A life I haven\'t started living yet' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'unfinished-things',
      nextStepId: 'living-scale',
    },
    {
      id: 'living-scale',
      type: 'scaleRating',
      prompt: "Right now — are you truly living or mostly postponing?",
      lowLabel: 'Mostly postponing',
      highLabel: 'Fully living',
      steps: 5,
      storeAs: 'living-level',
      responsesByRange: {
        low: "You've been saving your life for later. But later isn't guaranteed. Today is.",
        mid: "Some parts of your life are alive. Others are on hold. Death doesn't wait for you to be ready.",
        high: "You're already awake. This practice will sharpen that aliveness into something unshakeable.",
      },
      nextStepId: 'memento-insight',
    },
    {
      id: 'memento-insight',
      type: 'insight',
      text: "MEMENTO MORI — 'Remember you will die.'\n\nThis was not a Stoic punishment. It was the ultimate clarifier. When you remember death, everything fake falls away. Petty grudges. Status anxiety. Meaningless busyness. What remains is what actually matters.",
      source: 'Stoic Philosophy',
      style: 'principle',
      followUp: "The Stoics didn't meditate on death to feel sad. They did it to feel alive.",
      nextStepId: 'seneca-tapflow',
    },
    {
      id: 'seneca-tapflow',
      type: 'tapFlow',
      title: "Seneca's Morning Practice",
      instructions: [
        'Every morning, Seneca began the same way.',
        'He looked at the day ahead and asked: "What if this is the last one?"',
        '"Begin at once to live," he wrote.',
        '"Count each separate day as a separate life."',
        'Not someday. Not next year. Not when conditions are perfect.',
        'Today. This hour. This breath.',
        'Marcus Aurelius wrote the same truth:',
        '"Think of yourself as dead. You have lived your life."',
        '"Now, take what\'s left and live it properly."',
        'This is not darkness. This is the most radical form of gratitude.',
      ],
      closingText: "Every morning is a gift you've been opening without noticing.",
      style: 'cosmic',
      nextStepId: 'priority-choice',
    },
    {
      id: 'priority-choice',
      type: 'choice',
      instruction: "If you had limited time, what would change?",
      question: "What does memento mori clarify for you?",
      options: [
        {
          id: 'stop-postponing',
          label: 'I need to stop postponing what matters',
          subtext: 'The important things keep getting pushed to "someday"',
          nextStepId: 'postponing-insight',
          storeAs: 'mementoClarity',
        },
        {
          id: 'stop-caring',
          label: 'I need to stop caring about what doesn\'t matter',
          subtext: 'Too much energy goes to things that won\'t matter in a year',
          nextStepId: 'caring-insight',
          storeAs: 'mementoClarity',
        },
      ],
    },
    {
      id: 'postponing-insight',
      type: 'insight',
      text: "\"Someday\" is a disease. It's the most dangerous word in your vocabulary. Because someday feels safe — it carries the illusion of intention without the risk of action.\n\nBut someday never comes. There is only today. The conversation, the risk, the words you need to say — they are all waiting for you to stop pretending you have forever.",
      style: 'revelation',
      nextStepId: 'converge-insight',
    },
    {
      id: 'caring-insight',
      type: 'insight',
      text: "When you remember death, the false urgencies get stripped away like dead leaves. The social media drama. The comparison game. The grudge you've been nursing. The approval you've been chasing.\n\nNone of it survives contact with mortality. What remains is love, meaning, and the people who actually matter.",
      style: 'revelation',
      nextStepId: 'converge-insight',
    },
    {
      id: 'converge-insight',
      type: 'insight',
      text: "THE MORNING PRACTICE:\n\nEvery morning when you wake up, before you reach for your phone, pause. Feel the light. Feel your breath. And say to yourself: 'I am alive. This day is real. I will not waste it.'\n\nThat's memento mori. Not a death wish. A life wish.",
      style: 'principle',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "If you had one month left to live, what would you do THIS WEEK? Be specific. Not bucket-list fantasies — real actions you could take in the next seven days.",
      minimumWords: 8,
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Seneca lived two thousand years ago, but his words cut through time like a blade: 'It is not that we have a short time to live, but that we waste a great deal of it.' You just stopped wasting it, even if only for a moment. Carry that clarity into this week.",
        ],
        byChoice: {
          'stop-postponing': [
            "You named the disease: postponement. The things you wrote down in your reflection — those are the things that matter. Not someday. This week. Seneca would tell you: begin at once to live. The clock is already running.",
          ],
          'stop-caring': [
            "You chose to shed what doesn't matter. That's what death teaches us — not grief, but clarity. The drama, the comparison, the noise — it all falls away when you remember you're mortal. Keep only what survives that test.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      preText: "This is the most important thing you'll say today.",
      statement: "I am mortal. This day is real. I will not waste it on what does not matter.",
      confirmLabel: "I am alive",
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 8: THE REHEARSAL (Premeditatio Malorum)
// ─────────────────────────────────────────────────────────────────────────────

const lesson8: FlexibleLesson = {
  id: 'stoic-8-the-rehearsal',
  slug: 'the-rehearsal',
  order: 3,
  title: 'The Rehearsal',
  subtitle: 'Rehearse the worst. Become ready for anything.',
  description: 'Learn why the Stoics deliberately imagined the worst — and why it made them braver, not sadder.',
  coreConceptTag: 'premeditatio',
  xpReward: 22,
  estimatedMinutes: 6,
  thumbnail: { icon: '🎭', color: '#6d28d9' },
  teaserText: "Tomorrow you'll learn why the Stoics deliberately imagined the worst — and why it made them braver, not sadder.",
  exercises: stoicLesson8Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "A surgeon rehearses every cut before the blade touches skin. A pilot runs simulations of every engine failure before takeoff. A soldier drills every ambush scenario before deployment.\n\nBut you? You walk into your life every single day with zero rehearsal.",
      subtext: "The most important performance of your life, and you've never practiced.",
      continueLabel: "That's true",
      mood: 'tension',
      nextStepId: 'scenario-2',
    },
    {
      id: 'scenario-2',
      type: 'scenario',
      narrative: "The ancient Stoics spent their mornings doing something that sounds crazy: they deliberately imagined everything that could go wrong that day. Loss. Humiliation. Betrayal. Death.\n\nThis wasn't pessimism. It was the most radical form of readiness ever invented.",
      bridgeQuestion: "What if you stopped being ambushed by life and started rehearsing for it?",
      continueLabel: "Show me how",
      mood: 'curiosity',
      nextStepId: 'unprepared-check',
    },
    {
      id: 'unprepared-check',
      type: 'resonanceCheck',
      prompt: "What are you most unprepared for right now?",
      instruction: "Tap what makes your stomach tighten",
      options: [
        { id: 'income', text: 'Losing my income or financial stability' },
        { id: 'humiliation', text: 'Being publicly humiliated or embarrassed' },
        { id: 'relationship', text: 'A relationship ending unexpectedly' },
        { id: 'illness', text: 'Getting seriously ill or injured' },
        { id: 'betrayal', text: 'Being betrayed by someone I trust' },
        { id: 'failure', text: 'Failing deeply at something important' },
      ],
      minSelections: 1,
      maxSelections: 2,
      storeAs: 'unprepared-fears',
      nextStepId: 'readiness-scale',
    },
    {
      id: 'readiness-scale',
      type: 'scaleRating',
      prompt: "If the worst happened tomorrow, how ready would you be?",
      lowLabel: 'Completely unprepared',
      highLabel: 'I could handle it',
      steps: 5,
      storeAs: 'readiness-level',
      responsesByRange: {
        low: "That vulnerability isn't weakness — it's honesty. And honesty is where preparation begins.",
        mid: "You'd survive, but you'd be shaken. Today we build the kind of readiness that turns shaken into steady.",
        high: "You've already done some internal rehearsal. Today we make it deliberate and powerful.",
      },
      nextStepId: 'premeditatio-insight',
    },
    {
      id: 'premeditatio-insight',
      type: 'insight',
      text: "PREMEDITATIO MALORUM — 'The premeditation of evils.'\n\nThis isn't making a list of fears on a spreadsheet. It's LIVING them in your mind. Feeling the loss. Sitting in the discomfort. Letting the worst wash over you — so that when reality arrives, it finds someone who has already been there.",
      source: 'Seneca & Epictetus',
      style: 'principle',
      followUp: "Seneca wrote: 'We should toughen our minds beforehand. The blow is softened if you've been rehearsing for it.'",
      nextStepId: 'rehearsal-tapflow',
    },
    {
      id: 'rehearsal-tapflow',
      type: 'tapFlow',
      title: "A Guided Premeditatio",
      instructions: [
        'Close your eyes for a moment. Breathe.',
        'Imagine waking up tomorrow and the thing you fear most has happened.',
        'Don\'t look away. Stay with it.',
        'What do you see? What does the room look like?',
        'How does your body feel? Where is the weight?',
        'Let the full reality of it land.',
        'Now... what does the Stoic in you do?',
        'You breathe. You stand up. You face what\'s real.',
        'You don\'t pretend it\'s okay. You decide to be okay anyway.',
        'This is the rehearsal. This is how warriors are forged.',
      ],
      closingText: "You just survived the worst — in your mind. Now reality has less power over you.",
      style: 'fearless',
      nextStepId: 'response-choice',
    },
    {
      id: 'response-choice',
      type: 'choice',
      instruction: "After that rehearsal, what did you notice?",
      question: "What came up during the exercise?",
      options: [
        {
          id: 'felt-anxiety',
          label: 'I felt real anxiety',
          subtext: 'My body reacted as if it were actually happening',
          nextStepId: 'anxiety-insight',
          storeAs: 'rehearsalResponse',
        },
        {
          id: 'felt-calm',
          label: 'I felt strangely calm',
          subtext: 'Looking at it directly was less scary than avoiding it',
          nextStepId: 'calm-insight',
          storeAs: 'rehearsalResponse',
        },
      ],
    },
    {
      id: 'anxiety-insight',
      type: 'insight',
      text: "Good. The anxiety means the rehearsal worked. Your mind treated it as real — which means your mind is now slightly more prepared for it.\n\nThis is exactly how exposure works. Psychologists call it 'anxiety inoculation.' The Stoics discovered it two thousand years before modern therapy. Each time you rehearse the worst, its power over you shrinks a little more.",
      style: 'reframe',
      nextStepId: 'practice-insight',
    },
    {
      id: 'calm-insight',
      type: 'insight',
      text: "That calm you felt? It's the relief of finally facing what you've been running from. Most of our fear lives in the refusal to look. The moment you turn toward it, something shifts.\n\nThe monster under the bed is always smaller when you turn on the light. You just turned on the light.",
      style: 'revelation',
      nextStepId: 'practice-insight',
    },
    {
      id: 'practice-insight',
      type: 'insight',
      text: "THE DAILY PRACTICE:\n\nEvery morning, spend 60 seconds rehearsing one thing that could go wrong today. Not spiraling. Not catastrophizing. Deliberately facing it, feeling it, and then deciding how the strongest version of you would respond.\n\n60 seconds. That's all it takes to stop being ambushed by life.",
      style: 'principle',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "What is the worst thing you've been refusing to imagine? Write it down. Look at it. What happens when you stop running from it?",
      minimumWords: 5,
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Epictetus taught his students to rehearse difficulty every morning — not to darken their day, but to armor their spirit. You just did what most people spend their whole lives avoiding: you looked at the worst and didn't flinch. That changes everything.",
        ],
        byChoice: {
          'felt-anxiety': [
            "The anxiety you felt is proof your mind took the rehearsal seriously. That's the whole point. Each time you face it mentally, the real thing loses a fraction of its power. Soldiers know this. Athletes know this. Now you know it too. Keep rehearsing.",
          ],
          'felt-calm': [
            "You found something most people never discover: the worst isn't as terrifying when you look at it directly. The Stoics knew that avoidance feeds fear, while confrontation dissolves it. You just confronted your worst — and you're still standing. Remember this feeling.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      preText: "You have rehearsed the worst. You are no longer caught off guard.",
      statement: "I have rehearsed the worst. I am ready for anything. The blow is softened because I saw it coming.",
      confirmLabel: "I am prepared",
      style: 'strength',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 9: THE ROLES WE PLAY (Role Ethics)
// ─────────────────────────────────────────────────────────────────────────────

const lesson9: FlexibleLesson = {
  id: 'stoic-9-the-roles',
  slug: 'the-roles',
  order: 4,
  title: 'The Roles We Play',
  subtitle: 'Every role deserves your excellence',
  description: 'Discover why being different people in different situations is not hypocrisy — it is a Stoic practice.',
  coreConceptTag: 'role-ethics',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '🎭', color: '#8b5cf6' },
  teaserText: "Tomorrow you'll discover why being different people in different situations isn't fake — it's a Stoic practice.",
  exercises: stoicLesson9Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "Think about it: you're a completely different person at work than you are at home. Different with your parents than with your friends. Different online than in person. Different when you're leading than when you're following.\n\nIs that hypocrisy? Or is it something deeper?",
      subtext: "You contain multitudes. The Stoics knew why.",
      continueLabel: "I've wondered about this",
      mood: 'curiosity',
      nextStepId: 'role-check',
    },
    {
      id: 'role-check',
      type: 'resonanceCheck',
      prompt: "Which roles do you play in your life?",
      instruction: "Tap all that apply",
      options: [
        { id: 'parent', text: 'Parent — raising someone who depends on me' },
        { id: 'partner', text: 'Partner — building a life with someone' },
        { id: 'professional', text: 'Professional — earning, creating, contributing' },
        { id: 'friend', text: 'Friend — showing up for people I chose' },
        { id: 'child', text: 'Child or sibling — part of the family I was born into' },
        { id: 'leader', text: 'Leader — people look to me for direction' },
        { id: 'student', text: 'Student — still learning, still growing' },
        { id: 'citizen', text: 'Citizen — part of something bigger than myself' },
      ],
      minSelections: 1,
      maxSelections: 4,
      storeAs: 'life-roles',
      nextStepId: 'excellence-scale',
    },
    {
      id: 'excellence-scale',
      type: 'scaleRating',
      prompt: "How many of your roles are you playing with excellence versus neglecting?",
      lowLabel: 'Neglecting most',
      highLabel: 'Excelling in most',
      steps: 5,
      storeAs: 'role-excellence',
      responsesByRange: {
        low: "You're spread thin, and something important is being starved. Let's look at what the Stoics knew about this.",
        mid: "Some roles get your best. Others get whatever's left. The Stoics had a framework for this.",
        high: "You're bringing real effort to your roles. Let's make that effort even more intentional.",
      },
      nextStepId: 'role-ethics-insight',
    },
    {
      id: 'role-ethics-insight',
      type: 'insight',
      text: "ROLE ETHICS: The Stoics believed every person is assigned roles — some by nature, some by circumstance, some by choice. Parent. Professional. Friend. Citizen.\n\nVirtue doesn't mean being the same person everywhere. It means playing EACH role with excellence. The best version of you as a parent is different from the best version of you as a leader. And that's not fake — it's wise.",
      source: 'Epictetus',
      style: 'principle',
      followUp: "You don't owe every role the same energy. But you owe every role your best.",
      nextStepId: 'marcus-role-tapflow',
    },
    {
      id: 'marcus-role-tapflow',
      type: 'tapFlow',
      title: "Marcus: The Reluctant Emperor",
      instructions: [
        'Marcus Aurelius wanted to be a philosopher.',
        'He wanted a quiet life of books and thought.',
        'Instead, fate made him Emperor of Rome.',
        'He didn\'t choose the role. But he chose how to play it.',
        'Every morning, he reminded himself: this is the role assigned to me.',
        'Not the role I wanted. The role I was given.',
        'And he played it with everything he had.',
        'Philosopher by desire. Emperor by fate.',
        'He didn\'t resent the role. He honored it.',
        'That is role ethics: play the role you\'re given as if you chose it.',
      ],
      closingText: "Excellence is not about the role. It's about how you play it.",
      style: 'grounding',
      nextStepId: 'neglect-choice',
    },
    {
      id: 'neglect-choice',
      type: 'choice',
      instruction: "Where is your excellence falling short?",
      question: "Which area needs more of your virtue?",
      options: [
        {
          id: 'personal-role',
          label: 'A personal role — partner, parent, friend, family',
          subtext: 'The people closest to me get the leftovers',
          nextStepId: 'personal-insight',
          storeAs: 'neglectedRole',
        },
        {
          id: 'professional-role',
          label: 'A professional role — work, leadership, contribution',
          subtext: 'I\'m coasting where I should be striving',
          nextStepId: 'professional-insight',
          storeAs: 'neglectedRole',
        },
      ],
    },
    {
      id: 'personal-insight',
      type: 'insight',
      text: "This is the cruelest irony of modern life: the people who matter most get the worst version of you. You give your patience to strangers, your energy to your boss, your best hours to your career — and the people you love get whatever's left.\n\nEpictetus would say: every role deserves virtue. But the roles closest to your heart deserve it most.",
      style: 'revelation',
      nextStepId: 'reflection',
    },
    {
      id: 'professional-insight',
      type: 'insight',
      text: "Every role is a stage for virtue. Even the roles you didn't choose. Even the roles you resent. The Stoic doesn't say 'this job is beneath me.' The Stoic says 'how can I bring excellence to this role today?'\n\nMarcus didn't want to be emperor. But he became one of the greatest in history — because he played the role he was given, not the one he wished for.",
      style: 'revelation',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "Choose one role you've been neglecting. What would excellence look like in that role THIS WEEK? Be specific — not a vague intention, but a concrete action.",
      minimumWords: 5,
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Epictetus taught that life is like a play: you don't choose the role, but you choose how well you perform it. You just identified where your performance has been slipping. The question isn't whether you have too many roles — it's whether each one is getting the excellence it deserves.",
        ],
        byChoice: {
          'personal-role': [
            "You admitted that the people closest to you are getting the worst version of you. That's painful to see — but seeing it is the first step to changing it. This week, give one person in your life the version of you that they deserve. Not the leftovers. The real thing.",
          ],
          'professional-role': [
            "You recognized that you've been coasting in a role that deserves more. Marcus Aurelius spent twenty years as an emperor he never wanted to be — and he did it with excellence because the role demanded it. Your role demands it too. Show up this week like you chose it.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      preText: "This is your commitment to every version of yourself.",
      statement: "Every role I play deserves my full virtue. I will not reserve excellence for the roles I prefer.",
      confirmLabel: "I commit to excellence",
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// LESSON 10: THE WEB (Sympatheia)
// ─────────────────────────────────────────────────────────────────────────────

const lesson10: FlexibleLesson = {
  id: 'stoic-10-the-web',
  slug: 'the-web',
  order: 5,
  title: 'The Web',
  subtitle: 'Everything touches everything',
  description: 'See why your smallest actions ripple further than you ever imagined.',
  coreConceptTag: 'sympatheia',
  xpReward: 20,
  estimatedMinutes: 5,
  thumbnail: { icon: '🕸️', color: '#a78bfa' },
  teaserText: "Tomorrow you'll see why your smallest actions ripple further than you ever imagined.",
  exercises: stoicLesson10Exercises,
  steps: [
    {
      id: 'opening',
      type: 'scenario',
      narrative: "The barista who handed you coffee this morning? She's having the worst day of her life. Her mother was diagnosed yesterday. The driver who cut you off? He's rushing to the hospital where his child is in surgery. The colleague who snapped at you? He just got a call that his marriage is over.",
      subtext: "You'll never know. But your reaction to each of them rippled into their day.",
      continueLabel: "I never thought about it that way",
      mood: 'curiosity',
      nextStepId: 'scenario-2',
    },
    {
      id: 'scenario-2',
      type: 'scenario',
      narrative: "You never know the full story. Not of the stranger on the street, not of the person sitting next to you, not even of the people you think you know best.\n\nBut your response — your patience, your anger, your kindness, your indifference — is always a thread in someone else's tapestry.",
      bridgeQuestion: "What kind of thread are you weaving into the lives around you?",
      continueLabel: "Let me think about this",
      mood: 'curiosity',
      nextStepId: 'web-check',
    },
    {
      id: 'web-check',
      type: 'resonanceCheck',
      prompt: "Where have you felt the web of connection?",
      instruction: "Tap what you've experienced",
      options: [
        { id: 'stranger-kindness', text: 'A stranger\'s kindness changed my entire day' },
        { id: 'chain-reaction', text: 'I watched one comment create a chain reaction' },
        { id: 'mood-spread', text: 'My mood affected everyone around me' },
        { id: 'hidden-story', text: 'I learned someone\'s hidden story and everything made sense' },
        { id: 'connected', text: 'I felt connected to something larger than myself' },
      ],
      minSelections: 1,
      maxSelections: 3,
      storeAs: 'web-experiences',
      nextStepId: 'sympatheia-insight',
    },
    {
      id: 'sympatheia-insight',
      type: 'insight',
      text: "SYMPATHEIA — 'Universal interconnection.'\n\nMarcus Aurelius used this word to describe something the Stoics considered fundamental: everything in the cosmos is connected. Not in a vague, mystical way — in a real, physical way. Your actions affect others. Their actions affect you. The cosmos is one living organism, and you are a cell in it.",
      source: 'Marcus Aurelius',
      style: 'principle',
      followUp: "Marcus wrote: 'Frequently consider the connection of all things in the universe.' He meant it literally.",
      nextStepId: 'marcus-web-tapflow',
    },
    {
      id: 'marcus-web-tapflow',
      type: 'tapFlow',
      title: "Marcus Looks Over Rome",
      instructions: [
        'Picture Marcus Aurelius standing on his palace balcony at dawn.',
        'Below him: Rome. Seventy million people in the empire.',
        'Each one a thread. Each one connected to every other.',
        'The baker whose bread feeds the soldier.',
        'The soldier whose safety protects the baker.',
        'The teacher whose student becomes the doctor.',
        'The doctor who saves the teacher\'s child.',
        'Seventy million threads. One fabric.',
        'Marcus saw himself not above the web, but inside it.',
        'Every decision he made sent ripples through millions of lives.',
        'And so does every decision you make.',
      ],
      closingText: "You are not separate. You are a thread in everything.",
      style: 'cosmic',
      nextStepId: 'ripple-scale',
    },
    {
      id: 'ripple-scale',
      type: 'scaleRating',
      prompt: "How often do you consider the ripple effect of your actions on others?",
      lowLabel: 'Rarely',
      highLabel: 'Constantly',
      steps: 5,
      storeAs: 'ripple-awareness',
      responsesByRange: {
        low: "Most people never think about this. You're about to start seeing threads everywhere.",
        mid: "You're sometimes aware. After today, you won't be able to unsee the web.",
        high: "You already feel the connections. This lesson will give that awareness a name and a practice.",
      },
      nextStepId: 'thread-choice',
    },
    {
      id: 'thread-choice',
      type: 'choice',
      instruction: "When someone brings negativity to you, what do you do?",
      question: "How do you typically handle hostility or negativity from others?",
      options: [
        {
          id: 'match-energy',
          label: 'Match their energy — if they\'re hostile, I push back',
          subtext: 'They started it, so I respond in kind',
          nextStepId: 'extend-insight',
          storeAs: 'threadResponse',
        },
        {
          id: 'absorb-it',
          label: 'Absorb it — the thread stops with me',
          subtext: 'I try not to pass the negativity on',
          nextStepId: 'absorb-insight',
          storeAs: 'threadResponse',
        },
      ],
    },
    {
      id: 'extend-insight',
      type: 'insight',
      text: "When you match hostility with hostility, you extend the thread. The anger that started with someone's bad morning travels through you and into the next person. And the next. And the next.\n\nYou become a relay station for pain. The Stoic asks: do I want to be a relay station, or a transformer? Someone who takes negative energy and converts it into something better?",
      style: 'reframe',
      nextStepId: 'reflection',
    },
    {
      id: 'absorb-insight',
      type: 'insight',
      text: "When you absorb negativity instead of passing it on, you do something remarkable: you break the chain. The anger, the rudeness, the cruelty — it entered you and stopped. You transformed it.\n\nMarcus Aurelius called this being a gift to the cosmos. Not because you're passive — but because you're strong enough to take what's ugly and refuse to multiply it.",
      style: 'revelation',
      nextStepId: 'reflection',
    },
    {
      id: 'reflection',
      type: 'reflection',
      prompt: "Think of one interaction this week where your reaction rippled into someone else's day — for better or worse. Trace the thread. Where did it go? What did it carry?",
      minimumWords: 5,
      nextStepId: 'mentor',
    },
    {
      id: 'mentor',
      type: 'mentor',
      responses: {
        default: [
          "Marcus Aurelius governed an empire of seventy million people and still reminded himself daily that everything is connected. Your world is smaller — but the connections are just as real. Every interaction is a thread. Every response is a choice about what kind of fabric you're weaving.",
        ],
        byChoice: {
          'match-energy': [
            "You admitted that you sometimes extend the thread of negativity. That honesty matters. Now you can see it happening in real time — the anger enters you, and you have a choice: relay it or transform it. The Stoic transforms. It takes more strength, but it changes the web for everyone.",
          ],
          'absorb-it': [
            "You already practice what Marcus taught: being a place where negativity stops. That's not weakness — it's the greatest strength there is. You take the ugliness of the world and refuse to multiply it. The web is better because you're in it.",
          ],
        },
      },
    },
    {
      id: 'affirmation-step',
      type: 'affirmation',
      preText: "You are part of something vast.",
      statement: "I am a thread in the web of all things. My choices ripple beyond what I can see. I will weave with care.",
      confirmLabel: "I am connected",
      style: 'commitment',
      nextStepId: 'reward',
    },
    {
      id: 'reward',
      type: 'reward',
    },
  ] as LessonStep[],
};

// ─────────────────────────────────────────────────────────────────────────────
// ASSEMBLE CHAPTER 2: THE PHILOSOPHER'S FIRE
// ─────────────────────────────────────────────────────────────────────────────

export const stoicChapter2_PhilosophersFire: FlexibleChapter = {
  id: 'chapter-stoic-philosophers-fire',
  slug: 'philosophers-fire',
  name: "The Philosopher's Fire",
  subtitle: 'Philosophy that bleeds, breathes, and acts',
  description: 'Five lessons in applied Stoicism. Plan without attachment, meditate on death to ignite life, rehearse difficulty, play your roles with excellence, and see the cosmic web connecting everything.',
  order: 2,
  iconName: 'Flame',
  lessons: [lesson6, lesson7, lesson8, lesson9, lesson10],
};

export default stoicChapter2_PhilosophersFire;
